-- AlterTable
ALTER TABLE "LIBRARY_DOCUMENT" ADD COLUMN     "UID_LEGAL_BRANCH_LIBRARY_DOCUMENT" TEXT;

-- CreateIndex
CREATE INDEX "LIBRARY_DOCUMENT_UID_LEGAL_BRANCH_LIBRARY_DOCUMENT_idx" ON "LIBRARY_DOCUMENT"("UID_LEGAL_BRANCH_LIBRARY_DOCUMENT");

-- AddForeignKey
ALTER TABLE "LIBRARY_DOCUMENT" ADD CONSTRAINT "LIBRARY_DOCUMENT_UID_LEGAL_BRANCH_LIBRARY_DOCUMENT_fkey" FOREIGN KEY ("UID_LEGAL_BRANCH_LIBRARY_DOCUMENT") REFERENCES "LEGAL_BRANCH"("UID_LEGAL_BRANCH") ON DELETE SET NULL ON UPDATE CASCADE;
