-- CreateEnum
CREATE TYPE "ClientType" AS ENUM ('INDIVIDUAL', 'COMPANY');

-- CreateEnum
CREATE TYPE "ProcessStatus" AS ENUM ('ACTIVE', 'IN_REVIEW', 'CLOSED', 'ARCHIVED');

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "LogContext" ADD VALUE 'CLIENTS';
ALTER TYPE "LogContext" ADD VALUE 'PROCESSES';

-- AlterTable
ALTER TABLE "DOCUMENT" ADD COLUMN     "UID_LEGAL_PROCESS_DOCUMENT" TEXT;

-- CreateTable
CREATE TABLE "CLIENT" (
    "UID_CLIENT" TEXT NOT NULL,
    "NUM_ID_CLIENT" SERIAL NOT NULL,
    "UID_FIRM" TEXT NOT NULL,
    "STR_TYPE_CLIENT" "ClientType" NOT NULL,
    "STR_FIRST_NAME_CLIENT" TEXT,
    "STR_LAST_NAME_CLIENT" TEXT,
    "STR_COMPANY_NAME_CLIENT" TEXT,
    "STR_DOCUMENT_TYPE_CLIENT" TEXT,
    "STR_DOCUMENT_NUMBER_CLIENT" TEXT,
    "STR_EMAIL_CLIENT" TEXT,
    "STR_PHONE_CLIENT" TEXT,
    "STR_ADDRESS_CLIENT" TEXT,
    "STR_CITY_CLIENT" TEXT,
    "UID_CREATED_BY_CLIENT" TEXT NOT NULL,
    "DTM_DELETED_AT_CLIENT" TIMESTAMP(3),
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CLIENT_pkey" PRIMARY KEY ("UID_CLIENT")
);

-- CreateTable
CREATE TABLE "LEGAL_PROCESS" (
    "UID_LEGAL_PROCESS" TEXT NOT NULL,
    "NUM_ID_LEGAL_PROCESS" SERIAL NOT NULL,
    "UID_FIRM" TEXT NOT NULL,
    "UID_CLIENT" TEXT NOT NULL,
    "STR_TITLE_LEGAL_PROCESS" TEXT NOT NULL,
    "STR_DESCRIPTION_LEGAL_PROCESS" TEXT,
    "STR_REFERENCE_LEGAL_PROCESS" TEXT,
    "UID_LEGAL_BRANCH" TEXT,
    "STR_STATUS_LEGAL_PROCESS" "ProcessStatus" NOT NULL DEFAULT 'ACTIVE',
    "STR_COURT_LEGAL_PROCESS" TEXT,
    "STR_COUNTERPART_LEGAL_PROCESS" TEXT,
    "DTM_START_DATE_LEGAL_PROCESS" TIMESTAMP(3),
    "DTM_END_DATE_LEGAL_PROCESS" TIMESTAMP(3),
    "UID_ASSIGNED_TO_LEGAL_PROCESS" TEXT,
    "UID_CREATED_BY_LEGAL_PROCESS" TEXT NOT NULL,
    "DTM_DELETED_AT_LEGAL_PROCESS" TIMESTAMP(3),
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "LEGAL_PROCESS_pkey" PRIMARY KEY ("UID_LEGAL_PROCESS")
);

-- CreateTable
CREATE TABLE "PROCESS_TEMPLATE" (
    "UID_PROCESS_TEMPLATE" TEXT NOT NULL,
    "UID_LEGAL_PROCESS" TEXT NOT NULL,
    "UID_DOCUMENT_TEMPLATE" TEXT NOT NULL,
    "NUM_SORT_ORDER_PROCESS_TEMPLATE" INTEGER NOT NULL DEFAULT 0,
    "BOOL_IS_REQUIRED_PROCESS_TEMPLATE" BOOLEAN NOT NULL DEFAULT false,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PROCESS_TEMPLATE_pkey" PRIMARY KEY ("UID_PROCESS_TEMPLATE")
);

-- CreateTable
CREATE TABLE "CLIENT_FREQUENT_TEMPLATE" (
    "UID_CLIENT_FREQUENT_TEMPLATE" TEXT NOT NULL,
    "UID_CLIENT" TEXT NOT NULL,
    "UID_DOCUMENT_TEMPLATE" TEXT NOT NULL,
    "NUM_USE_COUNT_CLIENT_FREQUENT_TEMPLATE" INTEGER NOT NULL DEFAULT 1,
    "DTM_LAST_USED_AT_CLIENT_FREQUENT_TEMPLATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CLIENT_FREQUENT_TEMPLATE_pkey" PRIMARY KEY ("UID_CLIENT_FREQUENT_TEMPLATE")
);

-- CreateIndex
CREATE UNIQUE INDEX "CLIENT_NUM_ID_CLIENT_key" ON "CLIENT"("NUM_ID_CLIENT");

-- CreateIndex
CREATE INDEX "CLIENT_UID_FIRM_idx" ON "CLIENT"("UID_FIRM");

-- CreateIndex
CREATE INDEX "CLIENT_STR_TYPE_CLIENT_idx" ON "CLIENT"("STR_TYPE_CLIENT");

-- CreateIndex
CREATE INDEX "CLIENT_DTM_DELETED_AT_CLIENT_idx" ON "CLIENT"("DTM_DELETED_AT_CLIENT");

-- CreateIndex
CREATE UNIQUE INDEX "LEGAL_PROCESS_NUM_ID_LEGAL_PROCESS_key" ON "LEGAL_PROCESS"("NUM_ID_LEGAL_PROCESS");

-- CreateIndex
CREATE INDEX "LEGAL_PROCESS_UID_FIRM_idx" ON "LEGAL_PROCESS"("UID_FIRM");

-- CreateIndex
CREATE INDEX "LEGAL_PROCESS_UID_CLIENT_idx" ON "LEGAL_PROCESS"("UID_CLIENT");

-- CreateIndex
CREATE INDEX "LEGAL_PROCESS_STR_STATUS_LEGAL_PROCESS_idx" ON "LEGAL_PROCESS"("STR_STATUS_LEGAL_PROCESS");

-- CreateIndex
CREATE INDEX "LEGAL_PROCESS_UID_ASSIGNED_TO_LEGAL_PROCESS_idx" ON "LEGAL_PROCESS"("UID_ASSIGNED_TO_LEGAL_PROCESS");

-- CreateIndex
CREATE INDEX "LEGAL_PROCESS_DTM_DELETED_AT_LEGAL_PROCESS_idx" ON "LEGAL_PROCESS"("DTM_DELETED_AT_LEGAL_PROCESS");

-- CreateIndex
CREATE UNIQUE INDEX "PROCESS_TEMPLATE_UID_LEGAL_PROCESS_UID_DOCUMENT_TEMPLATE_key" ON "PROCESS_TEMPLATE"("UID_LEGAL_PROCESS", "UID_DOCUMENT_TEMPLATE");

-- CreateIndex
CREATE UNIQUE INDEX "CLIENT_FREQUENT_TEMPLATE_UID_CLIENT_UID_DOCUMENT_TEMPLATE_key" ON "CLIENT_FREQUENT_TEMPLATE"("UID_CLIENT", "UID_DOCUMENT_TEMPLATE");

-- CreateIndex
CREATE INDEX "DOCUMENT_UID_LEGAL_PROCESS_DOCUMENT_idx" ON "DOCUMENT"("UID_LEGAL_PROCESS_DOCUMENT");

-- AddForeignKey
ALTER TABLE "DOCUMENT" ADD CONSTRAINT "DOCUMENT_UID_LEGAL_PROCESS_DOCUMENT_fkey" FOREIGN KEY ("UID_LEGAL_PROCESS_DOCUMENT") REFERENCES "LEGAL_PROCESS"("UID_LEGAL_PROCESS") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CLIENT" ADD CONSTRAINT "CLIENT_UID_FIRM_fkey" FOREIGN KEY ("UID_FIRM") REFERENCES "FIRM"("UID_FIRM") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CLIENT" ADD CONSTRAINT "CLIENT_UID_CREATED_BY_CLIENT_fkey" FOREIGN KEY ("UID_CREATED_BY_CLIENT") REFERENCES "USER"("UID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LEGAL_PROCESS" ADD CONSTRAINT "LEGAL_PROCESS_UID_FIRM_fkey" FOREIGN KEY ("UID_FIRM") REFERENCES "FIRM"("UID_FIRM") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LEGAL_PROCESS" ADD CONSTRAINT "LEGAL_PROCESS_UID_CLIENT_fkey" FOREIGN KEY ("UID_CLIENT") REFERENCES "CLIENT"("UID_CLIENT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LEGAL_PROCESS" ADD CONSTRAINT "LEGAL_PROCESS_UID_LEGAL_BRANCH_fkey" FOREIGN KEY ("UID_LEGAL_BRANCH") REFERENCES "LEGAL_BRANCH"("UID_LEGAL_BRANCH") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LEGAL_PROCESS" ADD CONSTRAINT "LEGAL_PROCESS_UID_ASSIGNED_TO_LEGAL_PROCESS_fkey" FOREIGN KEY ("UID_ASSIGNED_TO_LEGAL_PROCESS") REFERENCES "USER"("UID_USER") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LEGAL_PROCESS" ADD CONSTRAINT "LEGAL_PROCESS_UID_CREATED_BY_LEGAL_PROCESS_fkey" FOREIGN KEY ("UID_CREATED_BY_LEGAL_PROCESS") REFERENCES "USER"("UID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROCESS_TEMPLATE" ADD CONSTRAINT "PROCESS_TEMPLATE_UID_LEGAL_PROCESS_fkey" FOREIGN KEY ("UID_LEGAL_PROCESS") REFERENCES "LEGAL_PROCESS"("UID_LEGAL_PROCESS") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROCESS_TEMPLATE" ADD CONSTRAINT "PROCESS_TEMPLATE_UID_DOCUMENT_TEMPLATE_fkey" FOREIGN KEY ("UID_DOCUMENT_TEMPLATE") REFERENCES "DOCUMENT_TEMPLATE"("UID_DOCUMENT_TEMPLATE") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CLIENT_FREQUENT_TEMPLATE" ADD CONSTRAINT "CLIENT_FREQUENT_TEMPLATE_UID_CLIENT_fkey" FOREIGN KEY ("UID_CLIENT") REFERENCES "CLIENT"("UID_CLIENT") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CLIENT_FREQUENT_TEMPLATE" ADD CONSTRAINT "CLIENT_FREQUENT_TEMPLATE_UID_DOCUMENT_TEMPLATE_fkey" FOREIGN KEY ("UID_DOCUMENT_TEMPLATE") REFERENCES "DOCUMENT_TEMPLATE"("UID_DOCUMENT_TEMPLATE") ON DELETE CASCADE ON UPDATE CASCADE;
