-- CreateTable
CREATE TABLE "DOCUMENT_FAVORITE" (
    "UID_DOCUMENT_FAVORITE" TEXT NOT NULL,
    "UID_DOCUMENT" TEXT NOT NULL,
    "UID_USER" TEXT NOT NULL,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "DOCUMENT_FAVORITE_pkey" PRIMARY KEY ("UID_DOCUMENT_FAVORITE")
);

-- CreateIndex
CREATE UNIQUE INDEX "DOCUMENT_FAVORITE_UID_DOCUMENT_UID_USER_key" ON "DOCUMENT_FAVORITE"("UID_DOCUMENT", "UID_USER");

-- AddForeignKey
ALTER TABLE "DOCUMENT_FAVORITE" ADD CONSTRAINT "DOCUMENT_FAVORITE_UID_DOCUMENT_fkey" FOREIGN KEY ("UID_DOCUMENT") REFERENCES "DOCUMENT"("UID_DOCUMENT") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCUMENT_FAVORITE" ADD CONSTRAINT "DOCUMENT_FAVORITE_UID_USER_fkey" FOREIGN KEY ("UID_USER") REFERENCES "USER"("UID_USER") ON DELETE CASCADE ON UPDATE CASCADE;
