-- CreateEnum
CREATE TYPE "BillableType" AS ENUM ('BILLABLE', 'NON_BILLABLE');

-- AlterTable
ALTER TABLE "FIRM" ADD COLUMN     "DEC_DAILY_BILLABLE_GOAL_HOURS_FIRM" DOUBLE PRECISION,
ADD COLUMN     "DEC_DAILY_NON_BILLABLE_GOAL_HOURS_FIRM" DOUBLE PRECISION,
ADD COLUMN     "DEC_FIRM_HOURLY_RATE_FIRM" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "LEGAL_PROCESS" ADD COLUMN     "DEC_PROCESS_VALUE_LEGAL_PROCESS" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "TIME_ENTRY" ADD COLUMN     "BOOL_IS_SHARED_TIME_ENTRY" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "STR_BILLABLE_TYPE_TIME_ENTRY" "BillableType" NOT NULL DEFAULT 'BILLABLE';

-- CreateTable
CREATE TABLE "PROCESS_VALUE_ENTRY" (
    "UID_PROCESS_VALUE_ENTRY" TEXT NOT NULL,
    "UID_LEGAL_PROCESS" TEXT NOT NULL,
    "UID_FIRM" TEXT NOT NULL,
    "DEC_AMOUNT_PROCESS_VALUE_ENTRY" DOUBLE PRECISION NOT NULL,
    "STR_DESCRIPTION_PROCESS_VALUE_ENTRY" TEXT NOT NULL,
    "UID_CREATED_BY_PROCESS_VALUE_ENTRY" TEXT NOT NULL,
    "DTM_DELETED_AT_PROCESS_VALUE_ENTRY" TIMESTAMP(3),
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PROCESS_VALUE_ENTRY_pkey" PRIMARY KEY ("UID_PROCESS_VALUE_ENTRY")
);

-- CreateTable
CREATE TABLE "TIME_ENTRY_PARTICIPANT" (
    "UID_TIME_ENTRY_PARTICIPANT" TEXT NOT NULL,
    "UID_TIME_ENTRY" TEXT NOT NULL,
    "UID_USER" TEXT NOT NULL,
    "UID_FIRM" TEXT NOT NULL,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TIME_ENTRY_PARTICIPANT_pkey" PRIMARY KEY ("UID_TIME_ENTRY_PARTICIPANT")
);

-- CreateIndex
CREATE INDEX "PROCESS_VALUE_ENTRY_UID_LEGAL_PROCESS_idx" ON "PROCESS_VALUE_ENTRY"("UID_LEGAL_PROCESS");

-- CreateIndex
CREATE INDEX "PROCESS_VALUE_ENTRY_DTM_DELETED_AT_PROCESS_VALUE_ENTRY_idx" ON "PROCESS_VALUE_ENTRY"("DTM_DELETED_AT_PROCESS_VALUE_ENTRY");

-- CreateIndex
CREATE INDEX "TIME_ENTRY_PARTICIPANT_UID_TIME_ENTRY_idx" ON "TIME_ENTRY_PARTICIPANT"("UID_TIME_ENTRY");

-- CreateIndex
CREATE INDEX "TIME_ENTRY_PARTICIPANT_UID_USER_idx" ON "TIME_ENTRY_PARTICIPANT"("UID_USER");

-- CreateIndex
CREATE UNIQUE INDEX "TIME_ENTRY_PARTICIPANT_UID_TIME_ENTRY_UID_USER_key" ON "TIME_ENTRY_PARTICIPANT"("UID_TIME_ENTRY", "UID_USER");

-- AddForeignKey
ALTER TABLE "PROCESS_VALUE_ENTRY" ADD CONSTRAINT "PROCESS_VALUE_ENTRY_UID_LEGAL_PROCESS_fkey" FOREIGN KEY ("UID_LEGAL_PROCESS") REFERENCES "LEGAL_PROCESS"("UID_LEGAL_PROCESS") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROCESS_VALUE_ENTRY" ADD CONSTRAINT "PROCESS_VALUE_ENTRY_UID_CREATED_BY_PROCESS_VALUE_ENTRY_fkey" FOREIGN KEY ("UID_CREATED_BY_PROCESS_VALUE_ENTRY") REFERENCES "USER"("UID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TIME_ENTRY_PARTICIPANT" ADD CONSTRAINT "TIME_ENTRY_PARTICIPANT_UID_TIME_ENTRY_fkey" FOREIGN KEY ("UID_TIME_ENTRY") REFERENCES "TIME_ENTRY"("UID_TIME_ENTRY") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TIME_ENTRY_PARTICIPANT" ADD CONSTRAINT "TIME_ENTRY_PARTICIPANT_UID_USER_fkey" FOREIGN KEY ("UID_USER") REFERENCES "USER"("UID_USER") ON DELETE CASCADE ON UPDATE CASCADE;
