-- DropForeignKey
ALTER TABLE "DOCUMENT" DROP CONSTRAINT "DOCUMENT_UID_FIRM_fkey";

-- DropForeignKey
ALTER TABLE "INVOICE" DROP CONSTRAINT "INVOICE_UID_FIRM_fkey";

-- DropForeignKey
ALTER TABLE "SUBSCRIPTION" DROP CONSTRAINT "SUBSCRIPTION_UID_FIRM_fkey";

-- AlterTable
ALTER TABLE "FIRM" ADD COLUMN     "DTM_PURGE_AT_FIRM" TIMESTAMP(3);

-- AddForeignKey
ALTER TABLE "DOCUMENT" ADD CONSTRAINT "DOCUMENT_UID_FIRM_fkey" FOREIGN KEY ("UID_FIRM") REFERENCES "FIRM"("UID_FIRM") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SUBSCRIPTION" ADD CONSTRAINT "SUBSCRIPTION_UID_FIRM_fkey" FOREIGN KEY ("UID_FIRM") REFERENCES "FIRM"("UID_FIRM") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INVOICE" ADD CONSTRAINT "INVOICE_UID_FIRM_fkey" FOREIGN KEY ("UID_FIRM") REFERENCES "FIRM"("UID_FIRM") ON DELETE CASCADE ON UPDATE CASCADE;
