-- CreateEnum
CREATE TYPE "ClientRegimeType" AS ENUM ('SIMPLIFIED', 'ORDINARY', 'GREAT_TAXPAYER', 'VAT_RESPONSIBLE', 'VAT_NON_RESPONSIBLE');

-- CreateEnum
CREATE TYPE "ClientDocumentType" AS ENUM ('RUT', 'CHAMBER_OF_COMMERCE', 'ID_DOCUMENT', 'OTHER');

-- CreateEnum
CREATE TYPE "ProcessBillingType" AS ENUM ('FIXED', 'HOURLY', 'MILESTONES', 'STAGES');

-- CreateEnum
CREATE TYPE "ProcessDocumentType" AS ENUM ('PROPOSAL', 'CONTRACT', 'OTHER');

-- AlterTable
ALTER TABLE "CLIENT" ADD COLUMN     "BOOL_IS_BUSINESS_GROUP_CLIENT" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "STR_REGIME_TYPE_CLIENT" "ClientRegimeType",
ADD COLUMN     "STR_SECTOR_CLIENT" TEXT,
ADD COLUMN     "UID_RESPONSIBLE_PARTNER_CLIENT" TEXT;

-- AlterTable
ALTER TABLE "LEGAL_PROCESS" ADD COLUMN     "BOOL_HAS_PARTIAL_PAYMENT_LEGAL_PROCESS" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "BOOL_IS_PRO_BONO_LEGAL_PROCESS" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "STR_BILLING_TYPE_LEGAL_PROCESS" "ProcessBillingType",
ADD COLUMN     "UID_BILLING_RESPONSIBLE_LEGAL_PROCESS" TEXT,
ADD COLUMN     "UID_ORIGINATOR_LEGAL_PROCESS" TEXT,
ADD COLUMN     "UID_PROCESS_CATEGORY" TEXT,
ADD COLUMN     "UID_RESPONSIBLE_PARTNER_LEGAL_PROCESS" TEXT;

-- CreateTable
CREATE TABLE "CLIENT_DOCUMENT" (
    "UID_CLIENT_DOCUMENT" TEXT NOT NULL,
    "NUM_ID_CLIENT_DOCUMENT" SERIAL NOT NULL,
    "UID_CLIENT" TEXT NOT NULL,
    "UID_UPLOADED_BY_CLIENT_DOCUMENT" TEXT NOT NULL,
    "STR_TYPE_CLIENT_DOCUMENT" "ClientDocumentType" NOT NULL,
    "STR_FILE_KEY_CLIENT_DOCUMENT" TEXT NOT NULL,
    "STR_FILE_URL_CLIENT_DOCUMENT" TEXT NOT NULL,
    "STR_FILE_NAME_CLIENT_DOCUMENT" TEXT NOT NULL,
    "NUM_FILE_SIZE_CLIENT_DOCUMENT" INTEGER NOT NULL,
    "STR_MIME_TYPE_CLIENT_DOCUMENT" TEXT NOT NULL,
    "DTM_DELETED_AT_CLIENT_DOCUMENT" TIMESTAMP(3),
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CLIENT_DOCUMENT_pkey" PRIMARY KEY ("UID_CLIENT_DOCUMENT")
);

-- CreateTable
CREATE TABLE "PROCESS_CATEGORY" (
    "UID_PROCESS_CATEGORY" TEXT NOT NULL,
    "NUM_ID_PROCESS_CATEGORY" SERIAL NOT NULL,
    "UID_FIRM" TEXT,
    "STR_NAME_PROCESS_CATEGORY" TEXT NOT NULL,
    "STR_SLUG_PROCESS_CATEGORY" TEXT NOT NULL,
    "BOOL_IS_SYSTEM_PROCESS_CATEGORY" BOOLEAN NOT NULL DEFAULT false,
    "BOOL_IS_ACTIVE_PROCESS_CATEGORY" BOOLEAN NOT NULL DEFAULT true,
    "NUM_SORT_ORDER_PROCESS_CATEGORY" INTEGER NOT NULL DEFAULT 0,
    "DTM_DELETED_AT_PROCESS_CATEGORY" TIMESTAMP(3),
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PROCESS_CATEGORY_pkey" PRIMARY KEY ("UID_PROCESS_CATEGORY")
);

-- CreateTable
CREATE TABLE "PROCESS_DOCUMENT" (
    "UID_PROCESS_DOCUMENT" TEXT NOT NULL,
    "NUM_ID_PROCESS_DOCUMENT" SERIAL NOT NULL,
    "UID_LEGAL_PROCESS" TEXT NOT NULL,
    "UID_UPLOADED_BY_PROCESS_DOCUMENT" TEXT NOT NULL,
    "STR_TYPE_PROCESS_DOCUMENT" "ProcessDocumentType" NOT NULL,
    "STR_FILE_KEY_PROCESS_DOCUMENT" TEXT NOT NULL,
    "STR_FILE_URL_PROCESS_DOCUMENT" TEXT NOT NULL,
    "STR_FILE_NAME_PROCESS_DOCUMENT" TEXT NOT NULL,
    "NUM_FILE_SIZE_PROCESS_DOCUMENT" INTEGER NOT NULL,
    "STR_MIME_TYPE_PROCESS_DOCUMENT" TEXT NOT NULL,
    "DTM_DELETED_AT_PROCESS_DOCUMENT" TIMESTAMP(3),
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PROCESS_DOCUMENT_pkey" PRIMARY KEY ("UID_PROCESS_DOCUMENT")
);

-- CreateIndex
CREATE INDEX "CLIENT_DOCUMENT_UID_CLIENT_idx" ON "CLIENT_DOCUMENT"("UID_CLIENT");

-- CreateIndex
CREATE INDEX "CLIENT_DOCUMENT_STR_TYPE_CLIENT_DOCUMENT_idx" ON "CLIENT_DOCUMENT"("STR_TYPE_CLIENT_DOCUMENT");

-- CreateIndex
CREATE INDEX "CLIENT_DOCUMENT_DTM_DELETED_AT_CLIENT_DOCUMENT_idx" ON "CLIENT_DOCUMENT"("DTM_DELETED_AT_CLIENT_DOCUMENT");

-- CreateIndex
CREATE INDEX "PROCESS_CATEGORY_STR_SLUG_PROCESS_CATEGORY_idx" ON "PROCESS_CATEGORY"("STR_SLUG_PROCESS_CATEGORY");

-- CreateIndex
CREATE INDEX "PROCESS_CATEGORY_UID_FIRM_idx" ON "PROCESS_CATEGORY"("UID_FIRM");

-- CreateIndex
CREATE INDEX "PROCESS_CATEGORY_BOOL_IS_SYSTEM_PROCESS_CATEGORY_idx" ON "PROCESS_CATEGORY"("BOOL_IS_SYSTEM_PROCESS_CATEGORY");

-- CreateIndex
CREATE INDEX "PROCESS_CATEGORY_DTM_DELETED_AT_PROCESS_CATEGORY_idx" ON "PROCESS_CATEGORY"("DTM_DELETED_AT_PROCESS_CATEGORY");

-- CreateIndex
CREATE INDEX "PROCESS_DOCUMENT_UID_LEGAL_PROCESS_idx" ON "PROCESS_DOCUMENT"("UID_LEGAL_PROCESS");

-- CreateIndex
CREATE INDEX "PROCESS_DOCUMENT_STR_TYPE_PROCESS_DOCUMENT_idx" ON "PROCESS_DOCUMENT"("STR_TYPE_PROCESS_DOCUMENT");

-- CreateIndex
CREATE INDEX "PROCESS_DOCUMENT_DTM_DELETED_AT_PROCESS_DOCUMENT_idx" ON "PROCESS_DOCUMENT"("DTM_DELETED_AT_PROCESS_DOCUMENT");

-- CreateIndex
CREATE INDEX "CLIENT_UID_RESPONSIBLE_PARTNER_CLIENT_idx" ON "CLIENT"("UID_RESPONSIBLE_PARTNER_CLIENT");

-- CreateIndex
CREATE INDEX "LEGAL_PROCESS_UID_PROCESS_CATEGORY_idx" ON "LEGAL_PROCESS"("UID_PROCESS_CATEGORY");

-- CreateIndex
CREATE INDEX "LEGAL_PROCESS_UID_RESPONSIBLE_PARTNER_LEGAL_PROCESS_idx" ON "LEGAL_PROCESS"("UID_RESPONSIBLE_PARTNER_LEGAL_PROCESS");

-- AddForeignKey
ALTER TABLE "CLIENT" ADD CONSTRAINT "CLIENT_UID_RESPONSIBLE_PARTNER_CLIENT_fkey" FOREIGN KEY ("UID_RESPONSIBLE_PARTNER_CLIENT") REFERENCES "FIRM_MEMBER"("UID_FIRM_MEMBER") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CLIENT_DOCUMENT" ADD CONSTRAINT "CLIENT_DOCUMENT_UID_CLIENT_fkey" FOREIGN KEY ("UID_CLIENT") REFERENCES "CLIENT"("UID_CLIENT") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CLIENT_DOCUMENT" ADD CONSTRAINT "CLIENT_DOCUMENT_UID_UPLOADED_BY_CLIENT_DOCUMENT_fkey" FOREIGN KEY ("UID_UPLOADED_BY_CLIENT_DOCUMENT") REFERENCES "USER"("UID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROCESS_CATEGORY" ADD CONSTRAINT "PROCESS_CATEGORY_UID_FIRM_fkey" FOREIGN KEY ("UID_FIRM") REFERENCES "FIRM"("UID_FIRM") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LEGAL_PROCESS" ADD CONSTRAINT "LEGAL_PROCESS_UID_PROCESS_CATEGORY_fkey" FOREIGN KEY ("UID_PROCESS_CATEGORY") REFERENCES "PROCESS_CATEGORY"("UID_PROCESS_CATEGORY") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LEGAL_PROCESS" ADD CONSTRAINT "LEGAL_PROCESS_UID_RESPONSIBLE_PARTNER_LEGAL_PROCESS_fkey" FOREIGN KEY ("UID_RESPONSIBLE_PARTNER_LEGAL_PROCESS") REFERENCES "FIRM_MEMBER"("UID_FIRM_MEMBER") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LEGAL_PROCESS" ADD CONSTRAINT "LEGAL_PROCESS_UID_ORIGINATOR_LEGAL_PROCESS_fkey" FOREIGN KEY ("UID_ORIGINATOR_LEGAL_PROCESS") REFERENCES "FIRM_MEMBER"("UID_FIRM_MEMBER") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LEGAL_PROCESS" ADD CONSTRAINT "LEGAL_PROCESS_UID_BILLING_RESPONSIBLE_LEGAL_PROCESS_fkey" FOREIGN KEY ("UID_BILLING_RESPONSIBLE_LEGAL_PROCESS") REFERENCES "FIRM_MEMBER"("UID_FIRM_MEMBER") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROCESS_DOCUMENT" ADD CONSTRAINT "PROCESS_DOCUMENT_UID_LEGAL_PROCESS_fkey" FOREIGN KEY ("UID_LEGAL_PROCESS") REFERENCES "LEGAL_PROCESS"("UID_LEGAL_PROCESS") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROCESS_DOCUMENT" ADD CONSTRAINT "PROCESS_DOCUMENT_UID_UPLOADED_BY_PROCESS_DOCUMENT_fkey" FOREIGN KEY ("UID_UPLOADED_BY_PROCESS_DOCUMENT") REFERENCES "USER"("UID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;
