-- AlterTable
ALTER TABLE "FIRM_MEMBER" ADD COLUMN     "UID_FIRM_ROLE" TEXT;

-- CreateTable
CREATE TABLE "MODULE" (
    "UID_MODULE" TEXT NOT NULL,
    "STR_KEY_MODULE" TEXT NOT NULL,
    "STR_LABEL_MODULE" TEXT NOT NULL,
    "STR_DESCRIPTION_MODULE" TEXT,
    "NUM_SORT_ORDER_MODULE" INTEGER NOT NULL DEFAULT 0,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "MODULE_pkey" PRIMARY KEY ("UID_MODULE")
);

-- CreateTable
CREATE TABLE "PERMISSION" (
    "UID_PERMISSION" TEXT NOT NULL,
    "STR_KEY_PERMISSION" TEXT NOT NULL,
    "STR_METHOD_PERMISSION" TEXT NOT NULL,
    "STR_PATH_PERMISSION" TEXT NOT NULL,
    "UID_MODULE" TEXT NOT NULL,
    "STR_LABEL_PERMISSION" TEXT NOT NULL,
    "BOOL_DEPRECATED_PERMISSION" BOOLEAN NOT NULL DEFAULT false,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PERMISSION_pkey" PRIMARY KEY ("UID_PERMISSION")
);

-- CreateTable
CREATE TABLE "FIRM_ROLE" (
    "UID_FIRM_ROLE" TEXT NOT NULL,
    "UID_FIRM" TEXT NOT NULL,
    "STR_NAME_FIRM_ROLE" TEXT NOT NULL,
    "STR_DESCRIPTION_FIRM_ROLE" TEXT,
    "STR_SLUG_FIRM_ROLE" TEXT,
    "BOOL_IS_SYSTEM_FIRM_ROLE" BOOLEAN NOT NULL DEFAULT false,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FIRM_ROLE_pkey" PRIMARY KEY ("UID_FIRM_ROLE")
);

-- CreateTable
CREATE TABLE "ROLE_PERMISSION" (
    "UID_FIRM_ROLE" TEXT NOT NULL,
    "UID_PERMISSION" TEXT NOT NULL,

    CONSTRAINT "ROLE_PERMISSION_pkey" PRIMARY KEY ("UID_FIRM_ROLE","UID_PERMISSION")
);

-- CreateIndex
CREATE UNIQUE INDEX "MODULE_STR_KEY_MODULE_key" ON "MODULE"("STR_KEY_MODULE");

-- CreateIndex
CREATE UNIQUE INDEX "PERMISSION_STR_KEY_PERMISSION_key" ON "PERMISSION"("STR_KEY_PERMISSION");

-- CreateIndex
CREATE INDEX "PERMISSION_UID_MODULE_idx" ON "PERMISSION"("UID_MODULE");

-- CreateIndex
CREATE INDEX "FIRM_ROLE_UID_FIRM_idx" ON "FIRM_ROLE"("UID_FIRM");

-- CreateIndex
CREATE UNIQUE INDEX "FIRM_ROLE_UID_FIRM_STR_NAME_FIRM_ROLE_key" ON "FIRM_ROLE"("UID_FIRM", "STR_NAME_FIRM_ROLE");

-- CreateIndex
CREATE INDEX "FIRM_MEMBER_UID_FIRM_ROLE_idx" ON "FIRM_MEMBER"("UID_FIRM_ROLE");

-- AddForeignKey
ALTER TABLE "FIRM_MEMBER" ADD CONSTRAINT "FIRM_MEMBER_UID_FIRM_ROLE_fkey" FOREIGN KEY ("UID_FIRM_ROLE") REFERENCES "FIRM_ROLE"("UID_FIRM_ROLE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PERMISSION" ADD CONSTRAINT "PERMISSION_UID_MODULE_fkey" FOREIGN KEY ("UID_MODULE") REFERENCES "MODULE"("UID_MODULE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FIRM_ROLE" ADD CONSTRAINT "FIRM_ROLE_UID_FIRM_fkey" FOREIGN KEY ("UID_FIRM") REFERENCES "FIRM"("UID_FIRM") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ROLE_PERMISSION" ADD CONSTRAINT "ROLE_PERMISSION_UID_FIRM_ROLE_fkey" FOREIGN KEY ("UID_FIRM_ROLE") REFERENCES "FIRM_ROLE"("UID_FIRM_ROLE") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ROLE_PERMISSION" ADD CONSTRAINT "ROLE_PERMISSION_UID_PERMISSION_fkey" FOREIGN KEY ("UID_PERMISSION") REFERENCES "PERMISSION"("UID_PERMISSION") ON DELETE CASCADE ON UPDATE CASCADE;
