-- CreateEnum
CREATE TYPE "ProcessTimelineEventType" AS ENUM ('ACTUACION', 'MILESTONE', 'DEADLINE', 'HEARING', 'NOTE', 'OTHER');

-- CreateEnum
CREATE TYPE "ProcessTimelineEventStatus" AS ENUM ('PENDING', 'COMPLETED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "ProcessTimelineAttachmentType" AS ENUM ('RULING', 'BRIEF', 'EVIDENCE', 'NOTIFICATION', 'DRAFT', 'OTHER');

-- CreateEnum
CREATE TYPE "ReminderChannel" AS ENUM ('EMAIL');

-- CreateEnum
CREATE TYPE "ReminderStatus" AS ENUM ('PENDING', 'SENT', 'FAILED', 'CANCELLED');

-- AlterTable
ALTER TABLE "NOTIFICATION_PREFERENCES" ADD COLUMN     "BOOL_EMAIL_PROCESS_REMINDERS_NOTIF_PREFS" BOOLEAN NOT NULL DEFAULT true;

-- CreateTable
CREATE TABLE "PROCESS_TIMELINE_EVENT" (
    "UID_PROCESS_TIMELINE_EVENT" TEXT NOT NULL,
    "NUM_ID_PROCESS_TIMELINE_EVENT" SERIAL NOT NULL,
    "UID_LEGAL_PROCESS" TEXT NOT NULL,
    "UID_FIRM" TEXT NOT NULL,
    "STR_TYPE_PROCESS_TIMELINE_EVENT" "ProcessTimelineEventType" NOT NULL DEFAULT 'ACTUACION',
    "STR_SUBTYPE_LABEL_PROCESS_TIMELINE_EVENT" TEXT,
    "STR_TITLE_PROCESS_TIMELINE_EVENT" TEXT NOT NULL,
    "STR_DESCRIPTION_PROCESS_TIMELINE_EVENT" TEXT,
    "DTM_EVENT_DATE_PROCESS_TIMELINE_EVENT" TIMESTAMP(3) NOT NULL,
    "BOOL_IS_DEADLINE_PROCESS_TIMELINE_EVENT" BOOLEAN NOT NULL DEFAULT false,
    "STR_STATUS_PROCESS_TIMELINE_EVENT" "ProcessTimelineEventStatus" NOT NULL DEFAULT 'COMPLETED',
    "STR_STATUS_LABEL_PROCESS_TIMELINE_EVENT" TEXT,
    "UID_RESPONSIBLE_PROCESS_TIMELINE_EVENT" TEXT,
    "UID_CREATED_BY_PROCESS_TIMELINE_EVENT" TEXT NOT NULL,
    "DTM_DELETED_AT_PROCESS_TIMELINE_EVENT" TIMESTAMP(3),
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PROCESS_TIMELINE_EVENT_pkey" PRIMARY KEY ("UID_PROCESS_TIMELINE_EVENT")
);

-- CreateTable
CREATE TABLE "PROCESS_TIMELINE_ATTACHMENT" (
    "UID_PROCESS_TIMELINE_ATTACHMENT" TEXT NOT NULL,
    "NUM_ID_PROCESS_TIMELINE_ATTACHMENT" SERIAL NOT NULL,
    "UID_PROCESS_TIMELINE_EVENT" TEXT NOT NULL,
    "UID_UPLOADED_BY_PROCESS_TIMELINE_ATTACHMENT" TEXT NOT NULL,
    "STR_TYPE_PROCESS_TIMELINE_ATTACHMENT" "ProcessTimelineAttachmentType" NOT NULL DEFAULT 'OTHER',
    "STR_FILE_KEY_PROCESS_TIMELINE_ATTACHMENT" TEXT NOT NULL,
    "STR_FILE_URL_PROCESS_TIMELINE_ATTACHMENT" TEXT NOT NULL,
    "STR_FILE_NAME_PROCESS_TIMELINE_ATTACHMENT" TEXT NOT NULL,
    "NUM_FILE_SIZE_PROCESS_TIMELINE_ATTACHMENT" INTEGER NOT NULL,
    "STR_MIME_TYPE_PROCESS_TIMELINE_ATTACHMENT" TEXT NOT NULL,
    "DTM_DELETED_AT_PROCESS_TIMELINE_ATTACHMENT" TIMESTAMP(3),
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PROCESS_TIMELINE_ATTACHMENT_pkey" PRIMARY KEY ("UID_PROCESS_TIMELINE_ATTACHMENT")
);

-- CreateTable
CREATE TABLE "PROCESS_TIMELINE_REMINDER" (
    "UID_PROCESS_TIMELINE_REMINDER" TEXT NOT NULL,
    "NUM_ID_PROCESS_TIMELINE_REMINDER" SERIAL NOT NULL,
    "UID_PROCESS_TIMELINE_EVENT" TEXT NOT NULL,
    "UID_LEGAL_PROCESS" TEXT NOT NULL,
    "STR_CHANNEL_PROCESS_TIMELINE_REMINDER" "ReminderChannel" NOT NULL DEFAULT 'EMAIL',
    "NUM_OFFSET_MINUTES_PROCESS_TIMELINE_REMINDER" INTEGER NOT NULL,
    "DTM_REMIND_AT_PROCESS_TIMELINE_REMINDER" TIMESTAMP(3) NOT NULL,
    "STR_RECIPIENT_EMAIL_PROCESS_TIMELINE_REMINDER" TEXT NOT NULL,
    "STR_STATUS_PROCESS_TIMELINE_REMINDER" "ReminderStatus" NOT NULL DEFAULT 'PENDING',
    "DTM_SENT_AT_PROCESS_TIMELINE_REMINDER" TIMESTAMP(3),
    "STR_LAST_ERROR_PROCESS_TIMELINE_REMINDER" TEXT,
    "UID_CREATED_BY_PROCESS_TIMELINE_REMINDER" TEXT NOT NULL,
    "DTM_DELETED_AT_PROCESS_TIMELINE_REMINDER" TIMESTAMP(3),
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PROCESS_TIMELINE_REMINDER_pkey" PRIMARY KEY ("UID_PROCESS_TIMELINE_REMINDER")
);

-- CreateIndex
CREATE INDEX "PROCESS_TIMELINE_EVENT_UID_LEGAL_PROCESS_idx" ON "PROCESS_TIMELINE_EVENT"("UID_LEGAL_PROCESS");

-- CreateIndex
CREATE INDEX "PROCESS_TIMELINE_EVENT_DTM_EVENT_DATE_PROCESS_TIMELINE_EVEN_idx" ON "PROCESS_TIMELINE_EVENT"("DTM_EVENT_DATE_PROCESS_TIMELINE_EVENT");

-- CreateIndex
CREATE INDEX "PROCESS_TIMELINE_EVENT_BOOL_IS_DEADLINE_PROCESS_TIMELINE_EV_idx" ON "PROCESS_TIMELINE_EVENT"("BOOL_IS_DEADLINE_PROCESS_TIMELINE_EVENT");

-- CreateIndex
CREATE INDEX "PROCESS_TIMELINE_EVENT_DTM_DELETED_AT_PROCESS_TIMELINE_EVEN_idx" ON "PROCESS_TIMELINE_EVENT"("DTM_DELETED_AT_PROCESS_TIMELINE_EVENT");

-- CreateIndex
CREATE INDEX "PROCESS_TIMELINE_ATTACHMENT_UID_PROCESS_TIMELINE_EVENT_idx" ON "PROCESS_TIMELINE_ATTACHMENT"("UID_PROCESS_TIMELINE_EVENT");

-- CreateIndex
CREATE INDEX "PROCESS_TIMELINE_ATTACHMENT_DTM_DELETED_AT_PROCESS_TIMELINE_idx" ON "PROCESS_TIMELINE_ATTACHMENT"("DTM_DELETED_AT_PROCESS_TIMELINE_ATTACHMENT");

-- CreateIndex
CREATE INDEX "PROCESS_TIMELINE_REMINDER_UID_PROCESS_TIMELINE_EVENT_idx" ON "PROCESS_TIMELINE_REMINDER"("UID_PROCESS_TIMELINE_EVENT");

-- CreateIndex
CREATE INDEX "PROCESS_TIMELINE_REMINDER_STR_STATUS_PROCESS_TIMELINE_REMIN_idx" ON "PROCESS_TIMELINE_REMINDER"("STR_STATUS_PROCESS_TIMELINE_REMINDER", "DTM_REMIND_AT_PROCESS_TIMELINE_REMINDER");

-- CreateIndex
CREATE INDEX "PROCESS_TIMELINE_REMINDER_DTM_DELETED_AT_PROCESS_TIMELINE_R_idx" ON "PROCESS_TIMELINE_REMINDER"("DTM_DELETED_AT_PROCESS_TIMELINE_REMINDER");

-- AddForeignKey
ALTER TABLE "PROCESS_TIMELINE_EVENT" ADD CONSTRAINT "PROCESS_TIMELINE_EVENT_UID_LEGAL_PROCESS_fkey" FOREIGN KEY ("UID_LEGAL_PROCESS") REFERENCES "LEGAL_PROCESS"("UID_LEGAL_PROCESS") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROCESS_TIMELINE_EVENT" ADD CONSTRAINT "PROCESS_TIMELINE_EVENT_UID_RESPONSIBLE_PROCESS_TIMELINE_EV_fkey" FOREIGN KEY ("UID_RESPONSIBLE_PROCESS_TIMELINE_EVENT") REFERENCES "FIRM_MEMBER"("UID_FIRM_MEMBER") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROCESS_TIMELINE_EVENT" ADD CONSTRAINT "PROCESS_TIMELINE_EVENT_UID_CREATED_BY_PROCESS_TIMELINE_EVE_fkey" FOREIGN KEY ("UID_CREATED_BY_PROCESS_TIMELINE_EVENT") REFERENCES "USER"("UID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROCESS_TIMELINE_ATTACHMENT" ADD CONSTRAINT "PROCESS_TIMELINE_ATTACHMENT_UID_PROCESS_TIMELINE_EVENT_fkey" FOREIGN KEY ("UID_PROCESS_TIMELINE_EVENT") REFERENCES "PROCESS_TIMELINE_EVENT"("UID_PROCESS_TIMELINE_EVENT") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROCESS_TIMELINE_ATTACHMENT" ADD CONSTRAINT "PROCESS_TIMELINE_ATTACHMENT_UID_UPLOADED_BY_PROCESS_TIMELI_fkey" FOREIGN KEY ("UID_UPLOADED_BY_PROCESS_TIMELINE_ATTACHMENT") REFERENCES "USER"("UID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROCESS_TIMELINE_REMINDER" ADD CONSTRAINT "PROCESS_TIMELINE_REMINDER_UID_PROCESS_TIMELINE_EVENT_fkey" FOREIGN KEY ("UID_PROCESS_TIMELINE_EVENT") REFERENCES "PROCESS_TIMELINE_EVENT"("UID_PROCESS_TIMELINE_EVENT") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROCESS_TIMELINE_REMINDER" ADD CONSTRAINT "PROCESS_TIMELINE_REMINDER_UID_LEGAL_PROCESS_fkey" FOREIGN KEY ("UID_LEGAL_PROCESS") REFERENCES "LEGAL_PROCESS"("UID_LEGAL_PROCESS") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROCESS_TIMELINE_REMINDER" ADD CONSTRAINT "PROCESS_TIMELINE_REMINDER_UID_CREATED_BY_PROCESS_TIMELINE__fkey" FOREIGN KEY ("UID_CREATED_BY_PROCESS_TIMELINE_REMINDER") REFERENCES "USER"("UID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;
