-- CreateEnum
CREATE TYPE "StorageObjectArea" AS ENUM ('PROCESS_DOCUMENT', 'TIMELINE_ATTACHMENT', 'CLIENT_DOCUMENT', 'LIBRARY_DOCUMENT');

-- AlterTable
ALTER TABLE "SUBSCRIPTION_PLAN" ADD COLUMN     "NUM_MAX_STORAGE_BYTES_PLAN" INTEGER;

-- CreateTable
CREATE TABLE "STORAGE_OBJECT" (
    "UID_STORAGE_OBJECT" TEXT NOT NULL,
    "NUM_ID_STORAGE_OBJECT" SERIAL NOT NULL,
    "UID_FIRM" TEXT NOT NULL,
    "STR_AREA_STORAGE_OBJECT" "StorageObjectArea" NOT NULL,
    "STR_OWNER_TYPE_STORAGE_OBJECT" TEXT NOT NULL,
    "STR_OWNER_ID_STORAGE_OBJECT" TEXT NOT NULL,
    "STR_FILE_KEY_STORAGE_OBJECT" TEXT NOT NULL,
    "STR_FILE_NAME_STORAGE_OBJECT" TEXT NOT NULL,
    "NUM_SIZE_BYTES_STORAGE_OBJECT" INTEGER NOT NULL,
    "STR_MIME_TYPE_STORAGE_OBJECT" TEXT NOT NULL,
    "UID_UPLOADED_BY_STORAGE_OBJECT" TEXT NOT NULL,
    "DTM_DELETED_AT_STORAGE_OBJECT" TIMESTAMP(3),
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "STORAGE_OBJECT_pkey" PRIMARY KEY ("UID_STORAGE_OBJECT")
);

-- CreateIndex
CREATE UNIQUE INDEX "STORAGE_OBJECT_STR_FILE_KEY_STORAGE_OBJECT_key" ON "STORAGE_OBJECT"("STR_FILE_KEY_STORAGE_OBJECT");

-- CreateIndex
CREATE INDEX "STORAGE_OBJECT_UID_FIRM_DTM_DELETED_AT_STORAGE_OBJECT_idx" ON "STORAGE_OBJECT"("UID_FIRM", "DTM_DELETED_AT_STORAGE_OBJECT");

-- CreateIndex
CREATE INDEX "STORAGE_OBJECT_DTM_DELETED_AT_STORAGE_OBJECT_idx" ON "STORAGE_OBJECT"("DTM_DELETED_AT_STORAGE_OBJECT");

-- AddForeignKey
ALTER TABLE "STORAGE_OBJECT" ADD CONSTRAINT "STORAGE_OBJECT_UID_FIRM_fkey" FOREIGN KEY ("UID_FIRM") REFERENCES "FIRM"("UID_FIRM") ON DELETE CASCADE ON UPDATE CASCADE;
