-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- CreateEnum
CREATE TYPE "LibraryDocumentType" AS ENUM ('LAW', 'DECREE', 'RESOLUTION', 'CIRCULAR', 'RULING', 'JURISPRUDENCE', 'DOCTRINE', 'CONTRACT', 'OTHER');

-- CreateTable
CREATE TABLE "LIBRARY_DOCUMENT" (
    "UID_LIBRARY_DOCUMENT" TEXT NOT NULL,
    "NUM_ID_LIBRARY_DOCUMENT" SERIAL NOT NULL,
    "UID_FIRM" TEXT NOT NULL,
    "UID_UPLOADED_BY_LIBRARY_DOCUMENT" TEXT NOT NULL,
    "STR_TITLE_LIBRARY_DOCUMENT" TEXT NOT NULL,
    "STR_DESCRIPTION_LIBRARY_DOCUMENT" TEXT,
    "STR_TYPE_LIBRARY_DOCUMENT" "LibraryDocumentType" NOT NULL,
    "STR_FILE_KEY_LIBRARY_DOCUMENT" TEXT NOT NULL,
    "STR_FILE_URL_LIBRARY_DOCUMENT" TEXT NOT NULL,
    "STR_FILE_NAME_LIBRARY_DOCUMENT" TEXT NOT NULL,
    "NUM_FILE_SIZE_LIBRARY_DOCUMENT" INTEGER NOT NULL,
    "STR_MIME_TYPE_LIBRARY_DOCUMENT" TEXT NOT NULL,
    "BOOL_IS_INDEXED_LIBRARY_DOCUMENT" BOOLEAN NOT NULL DEFAULT false,
    "DTM_DELETED_AT_LIBRARY_DOCUMENT" TIMESTAMP(3),
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "LIBRARY_DOCUMENT_pkey" PRIMARY KEY ("UID_LIBRARY_DOCUMENT")
);

-- CreateTable
CREATE TABLE "LIBRARY_CHUNK" (
    "UID_LIBRARY_CHUNK" TEXT NOT NULL,
    "UID_LIBRARY_DOCUMENT" TEXT NOT NULL,
    "NUM_CHUNK_INDEX_LIBRARY_CHUNK" INTEGER NOT NULL,
    "STR_CONTENT_LIBRARY_CHUNK" TEXT NOT NULL,
    "embedding" vector(1536) NOT NULL,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "LIBRARY_CHUNK_pkey" PRIMARY KEY ("UID_LIBRARY_CHUNK")
);

-- CreateIndex
CREATE UNIQUE INDEX "LIBRARY_DOCUMENT_NUM_ID_LIBRARY_DOCUMENT_key" ON "LIBRARY_DOCUMENT"("NUM_ID_LIBRARY_DOCUMENT");

-- CreateIndex
CREATE INDEX "LIBRARY_DOCUMENT_UID_FIRM_idx" ON "LIBRARY_DOCUMENT"("UID_FIRM");

-- CreateIndex
CREATE INDEX "LIBRARY_DOCUMENT_STR_TYPE_LIBRARY_DOCUMENT_idx" ON "LIBRARY_DOCUMENT"("STR_TYPE_LIBRARY_DOCUMENT");

-- CreateIndex
CREATE INDEX "LIBRARY_DOCUMENT_BOOL_IS_INDEXED_LIBRARY_DOCUMENT_idx" ON "LIBRARY_DOCUMENT"("BOOL_IS_INDEXED_LIBRARY_DOCUMENT");

-- CreateIndex
CREATE INDEX "LIBRARY_DOCUMENT_DTM_DELETED_AT_LIBRARY_DOCUMENT_idx" ON "LIBRARY_DOCUMENT"("DTM_DELETED_AT_LIBRARY_DOCUMENT");

-- CreateIndex
CREATE INDEX "LIBRARY_CHUNK_UID_LIBRARY_DOCUMENT_idx" ON "LIBRARY_CHUNK"("UID_LIBRARY_DOCUMENT");

-- AddForeignKey
ALTER TABLE "LIBRARY_DOCUMENT" ADD CONSTRAINT "LIBRARY_DOCUMENT_UID_FIRM_fkey" FOREIGN KEY ("UID_FIRM") REFERENCES "FIRM"("UID_FIRM") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LIBRARY_DOCUMENT" ADD CONSTRAINT "LIBRARY_DOCUMENT_UID_UPLOADED_BY_LIBRARY_DOCUMENT_fkey" FOREIGN KEY ("UID_UPLOADED_BY_LIBRARY_DOCUMENT") REFERENCES "USER"("UID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LIBRARY_CHUNK" ADD CONSTRAINT "LIBRARY_CHUNK_UID_LIBRARY_DOCUMENT_fkey" FOREIGN KEY ("UID_LIBRARY_DOCUMENT") REFERENCES "LIBRARY_DOCUMENT"("UID_LIBRARY_DOCUMENT") ON DELETE CASCADE ON UPDATE CASCADE;
