-- AlterTable
ALTER TABLE "SUBSCRIPTION" ADD COLUMN     "DTM_AI_TOKENS_DAILY_RESET_AT_SUBSCRIPTION" TIMESTAMP(3),
ADD COLUMN     "DTM_AI_TOKENS_MONTHLY_RESET_AT_SUBSCRIPTION" TIMESTAMP(3),
ADD COLUMN     "DTM_AI_TOKENS_WEEKLY_RESET_AT_SUBSCRIPTION" TIMESTAMP(3),
ADD COLUMN     "NUM_AI_TOKENS_USED_DAILY_SUBSCRIPTION" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "NUM_AI_TOKENS_USED_MONTHLY_SUBSCRIPTION" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "NUM_AI_TOKENS_USED_WEEKLY_SUBSCRIPTION" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "SUBSCRIPTION_PLAN" ADD COLUMN     "NUM_MAX_AI_TOKENS_DAILY_PLAN" INTEGER,
ADD COLUMN     "NUM_MAX_AI_TOKENS_MONTHLY_PLAN" INTEGER,
ADD COLUMN     "NUM_MAX_AI_TOKENS_WEEKLY_PLAN" INTEGER;
