-- CreateEnum
CREATE TYPE "FirmMemberRole" AS ENUM ('ADMIN', 'LAWYER', 'ASSISTANT', 'INTERN');

-- CreateEnum
CREATE TYPE "FirmMemberStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'PENDING');

-- CreateEnum
CREATE TYPE "TemplateOrigin" AS ENUM ('SYSTEM', 'FIRM_CUSTOM', 'FIRM_COPY');

-- CreateEnum
CREATE TYPE "DocumentStatus" AS ENUM ('DRAFT', 'COMPLETED', 'REVISION', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "SignatureType" AS ENUM ('DRAW', 'TYPE', 'UPLOAD');

-- CreateEnum
CREATE TYPE "SubscriptionStatus" AS ENUM ('TRIAL', 'ACTIVE', 'CANCELLED', 'EXPIRED', 'PAST_DUE');

-- CreateEnum
CREATE TYPE "BillingCycle" AS ENUM ('MONTHLY', 'ANNUALLY');

-- CreateEnum
CREATE TYPE "InvoiceStatus" AS ENUM ('PENDING', 'PAID', 'FAILED', 'REFUNDED', 'VOIDED');

-- CreateEnum
CREATE TYPE "PaymentMethodType" AS ENUM ('CARD', 'BANK_TRANSFER', 'PSE');

-- CreateEnum
CREATE TYPE "LogLevel" AS ENUM ('DEBUG', 'INFO', 'WARN', 'ERROR', 'FATAL');

-- CreateEnum
CREATE TYPE "LogContext" AS ENUM ('AUTH', 'USER_MANAGEMENT', 'DOCUMENTS', 'TEMPLATES', 'FIRM', 'SUBSCRIPTIONS', 'SYSTEM', 'SECURITY');

-- CreateEnum
CREATE TYPE "ActionType" AS ENUM ('CREATE', 'READ', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'EXPORT', 'IMPORT', 'RESTORE');

-- CreateTable
CREATE TABLE "USER" (
    "UID_USER" TEXT NOT NULL,
    "NUM_ID_USER" SERIAL NOT NULL,
    "STR_FIRST_NAME_USER" TEXT NOT NULL,
    "STR_LAST_NAME_USER" TEXT NOT NULL,
    "STR_EMAIL_USER" TEXT NOT NULL,
    "STR_PHONE_USER" TEXT,
    "STR_ADDRESS_USER" TEXT,
    "STR_CITY_USER" TEXT,
    "STR_COUNTRY_USER" TEXT DEFAULT 'Colombia',
    "DTM_BIRTH_DATE_USER" TIMESTAMP(3),
    "STR_BIO_USER" TEXT,
    "STR_AVATAR_URL_USER" TEXT,
    "STR_CLOUD_PUBLIC_ID_USER" TEXT,
    "DTM_LAST_LOGIN_AT" TIMESTAMP(3),
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "USER_pkey" PRIMARY KEY ("UID_USER")
);

-- CreateTable
CREATE TABLE "CREDENTIALS" (
    "UID_CREDENTIALS" TEXT NOT NULL,
    "UID_USER" TEXT NOT NULL,
    "STR_EMAIL_CREDENTIALS" TEXT NOT NULL,
    "STR_PASSWORD" TEXT NOT NULL,
    "BOOL_IS_EMAIL_VERIFIED" BOOLEAN NOT NULL DEFAULT false,
    "STR_EMAIL_VERIFY_TOKEN" TEXT,
    "STR_RESET_TOKEN" TEXT,
    "DTM_RESET_TOKEN_EXPIRY" TIMESTAMP(3),
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CREDENTIALS_pkey" PRIMARY KEY ("UID_CREDENTIALS")
);

-- CreateTable
CREATE TABLE "REFRESH_TOKEN" (
    "UID_REFRESH_TOKEN" TEXT NOT NULL,
    "UID_CREDENTIALS" TEXT NOT NULL,
    "STR_TOKEN_HASH" TEXT NOT NULL,
    "DTM_EXPIRES_AT" TIMESTAMP(3) NOT NULL,
    "DTM_REVOKED_AT" TIMESTAMP(3),
    "STR_USER_AGENT" TEXT,
    "STR_IP_ADDRESS" TEXT,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "REFRESH_TOKEN_pkey" PRIMARY KEY ("UID_REFRESH_TOKEN")
);

-- CreateTable
CREATE TABLE "NOTIFICATION_PREFERENCES" (
    "UID_NOTIFICATION_PREFS" TEXT NOT NULL,
    "UID_USER" TEXT NOT NULL,
    "BOOL_EMAIL_NEW_DOCUMENT" BOOLEAN NOT NULL DEFAULT true,
    "BOOL_EMAIL_DOCUMENT_SHARED" BOOLEAN NOT NULL DEFAULT true,
    "BOOL_EMAIL_TEMPLATE_UPDATED" BOOLEAN NOT NULL DEFAULT true,
    "BOOL_EMAIL_TEAM_INVITE" BOOLEAN NOT NULL DEFAULT true,
    "BOOL_EMAIL_BILLING" BOOLEAN NOT NULL DEFAULT true,
    "BOOL_EMAIL_LEGAL_UPDATES" BOOLEAN NOT NULL DEFAULT false,
    "BOOL_INAPP_NEW_DOCUMENT" BOOLEAN NOT NULL DEFAULT true,
    "BOOL_INAPP_DOCUMENT_SHARED" BOOLEAN NOT NULL DEFAULT true,
    "BOOL_INAPP_TEAM_ACTIVITY" BOOLEAN NOT NULL DEFAULT true,
    "BOOL_INAPP_BILLING" BOOLEAN NOT NULL DEFAULT true,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "NOTIFICATION_PREFERENCES_pkey" PRIMARY KEY ("UID_NOTIFICATION_PREFS")
);

-- CreateTable
CREATE TABLE "SECURITY_SETTINGS" (
    "UID_SECURITY_SETTINGS" TEXT NOT NULL,
    "UID_USER" TEXT NOT NULL,
    "BOOL_TWO_FACTOR_ENABLED" BOOLEAN NOT NULL DEFAULT false,
    "STR_TWO_FACTOR_METHOD" TEXT NOT NULL DEFAULT 'email',
    "STR_TWO_FACTOR_SECRET" TEXT,
    "NUM_SESSION_TIMEOUT_MINS" INTEGER NOT NULL DEFAULT 480,
    "BOOL_LOGIN_NOTIFICATIONS" BOOLEAN NOT NULL DEFAULT true,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SECURITY_SETTINGS_pkey" PRIMARY KEY ("UID_SECURITY_SETTINGS")
);

-- CreateTable
CREATE TABLE "FIRM" (
    "UID_FIRM" TEXT NOT NULL,
    "NUM_ID_FIRM" SERIAL NOT NULL,
    "STR_NAME_FIRM" TEXT NOT NULL,
    "STR_LEGAL_NAME_FIRM" TEXT,
    "STR_NIT_FIRM" TEXT,
    "STR_ADDRESS_FIRM" TEXT,
    "STR_CITY_FIRM" TEXT,
    "STR_COUNTRY_FIRM" TEXT DEFAULT 'Colombia',
    "STR_PHONE_FIRM" TEXT,
    "STR_EMAIL_FIRM" TEXT,
    "STR_WEBSITE_FIRM" TEXT,
    "STR_DESCRIPTION_FIRM" TEXT,
    "STR_LOGO_URL_FIRM" TEXT,
    "STR_CLOUD_PUBLIC_ID_FIRM" TEXT,
    "UID_CREATED_BY" TEXT NOT NULL,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FIRM_pkey" PRIMARY KEY ("UID_FIRM")
);

-- CreateTable
CREATE TABLE "FIRM_SPECIALTY" (
    "UID_FIRM_SPECIALTY" TEXT NOT NULL,
    "UID_FIRM" TEXT NOT NULL,
    "STR_SPECIALTY" TEXT NOT NULL,

    CONSTRAINT "FIRM_SPECIALTY_pkey" PRIMARY KEY ("UID_FIRM_SPECIALTY")
);

-- CreateTable
CREATE TABLE "FIRM_MEMBER" (
    "UID_FIRM_MEMBER" TEXT NOT NULL,
    "UID_FIRM" TEXT NOT NULL,
    "UID_USER" TEXT,
    "STR_ROLE_FIRM_MEMBER" "FirmMemberRole" NOT NULL DEFAULT 'ASSISTANT',
    "STR_STATUS_FIRM_MEMBER" "FirmMemberStatus" NOT NULL DEFAULT 'PENDING',
    "STR_INVITE_EMAIL" TEXT,
    "STR_INVITE_TOKEN" TEXT,
    "DTM_INVITE_EXPIRES_AT" TIMESTAMP(3),
    "DTM_JOINED_AT" TIMESTAMP(3),
    "DTM_LAST_ACTIVE_AT" TIMESTAMP(3),
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FIRM_MEMBER_pkey" PRIMARY KEY ("UID_FIRM_MEMBER")
);

-- CreateTable
CREATE TABLE "LEGAL_BRANCH" (
    "UID_LEGAL_BRANCH" TEXT NOT NULL,
    "NUM_ID_LEGAL_BRANCH" SERIAL NOT NULL,
    "STR_NAME_LEGAL_BRANCH" TEXT NOT NULL,
    "STR_SLUG_LEGAL_BRANCH" TEXT NOT NULL,
    "STR_DESCRIPTION_LEGAL_BRANCH" TEXT,
    "STR_ICON_LEGAL_BRANCH" TEXT,
    "STR_COLOR_LEGAL_BRANCH" TEXT,
    "BOOL_IS_SYSTEM_BRANCH" BOOLEAN NOT NULL DEFAULT false,
    "UID_FIRM" TEXT,
    "BOOL_IS_ACTIVE_BRANCH" BOOLEAN NOT NULL DEFAULT true,
    "NUM_SORT_ORDER_BRANCH" INTEGER NOT NULL DEFAULT 0,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "LEGAL_BRANCH_pkey" PRIMARY KEY ("UID_LEGAL_BRANCH")
);

-- CreateTable
CREATE TABLE "DOCUMENT_TEMPLATE" (
    "UID_DOCUMENT_TEMPLATE" TEXT NOT NULL,
    "NUM_ID_DOCUMENT_TEMPLATE" SERIAL NOT NULL,
    "STR_DOCUMENT_TYPE" TEXT NOT NULL,
    "STR_VERSION_TEMPLATE" TEXT NOT NULL DEFAULT '1.0',
    "STR_TITLE_TEMPLATE" TEXT NOT NULL,
    "UID_LEGAL_BRANCH" TEXT NOT NULL,
    "STR_SUBCATEGORY_TEMPLATE" TEXT,
    "JSON_APPLICABLE_REGULATIONS" JSONB NOT NULL DEFAULT '[]',
    "BOOL_REQUIRES_REGISTRATION" BOOLEAN NOT NULL DEFAULT false,
    "BOOL_LEGAL_VALIDITY" BOOLEAN NOT NULL DEFAULT true,
    "JSON_VARIABLE_FIELDS" JSONB NOT NULL DEFAULT '{}',
    "STR_TEXT_TEMPLATE" TEXT,
    "STR_ORIGIN_TEMPLATE" "TemplateOrigin" NOT NULL DEFAULT 'SYSTEM',
    "UID_PARENT_TEMPLATE" TEXT,
    "UID_FIRM" TEXT,
    "UID_CREATED_BY" TEXT,
    "BOOL_IS_ACTIVE_TEMPLATE" BOOLEAN NOT NULL DEFAULT true,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DOCUMENT_TEMPLATE_pkey" PRIMARY KEY ("UID_DOCUMENT_TEMPLATE")
);

-- CreateTable
CREATE TABLE "TEMPLATE_FAVORITE" (
    "UID_TEMPLATE_FAVORITE" TEXT NOT NULL,
    "UID_DOCUMENT_TEMPLATE" TEXT NOT NULL,
    "UID_USER" TEXT NOT NULL,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TEMPLATE_FAVORITE_pkey" PRIMARY KEY ("UID_TEMPLATE_FAVORITE")
);

-- CreateTable
CREATE TABLE "DOCUMENT" (
    "UID_DOCUMENT" TEXT NOT NULL,
    "NUM_ID_DOCUMENT" SERIAL NOT NULL,
    "STR_TITLE_DOCUMENT" TEXT NOT NULL,
    "UID_DOCUMENT_TEMPLATE" TEXT,
    "STR_DOCUMENT_TYPE" TEXT NOT NULL,
    "UID_LEGAL_BRANCH" TEXT,
    "JSON_FORM_DATA" JSONB NOT NULL DEFAULT '{}',
    "STR_CONTENT_DOCUMENT" TEXT,
    "BOOL_HAS_CUSTOM_CONTENT" BOOLEAN NOT NULL DEFAULT false,
    "STR_STATUS_DOCUMENT" "DocumentStatus" NOT NULL DEFAULT 'DRAFT',
    "UID_FIRM" TEXT NOT NULL,
    "UID_CREATED_BY" TEXT NOT NULL,
    "DTM_DELETED_AT" TIMESTAMP(3),
    "DTM_TRASH_EXPIRES_AT" TIMESTAMP(3),
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DOCUMENT_pkey" PRIMARY KEY ("UID_DOCUMENT")
);

-- CreateTable
CREATE TABLE "DIGITAL_SIGNATURE" (
    "UID_DIGITAL_SIGNATURE" TEXT NOT NULL,
    "UID_USER" TEXT NOT NULL,
    "STR_NAME_SIGNATURE" TEXT NOT NULL,
    "STR_TYPE_SIGNATURE" "SignatureType" NOT NULL,
    "STR_CONTENT_SIGNATURE" TEXT NOT NULL,
    "STR_FONT_SIGNATURE" TEXT,
    "STR_CLOUD_PUBLIC_ID_SIGNATURE" TEXT,
    "BOOL_IS_DEFAULT_SIGNATURE" BOOLEAN NOT NULL DEFAULT false,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DIGITAL_SIGNATURE_pkey" PRIMARY KEY ("UID_DIGITAL_SIGNATURE")
);

-- CreateTable
CREATE TABLE "SUBSCRIPTION_PLAN" (
    "UID_SUBSCRIPTION_PLAN" TEXT NOT NULL,
    "STR_NAME_PLAN" TEXT NOT NULL,
    "STR_DISPLAY_NAME_PLAN" TEXT NOT NULL,
    "STR_DESCRIPTION_PLAN" TEXT,
    "NUM_PRICE_MONTHLY" DECIMAL(65,30),
    "NUM_PRICE_ANNUALLY" DECIMAL(65,30),
    "NUM_MAX_DOCUMENTS" INTEGER,
    "NUM_MAX_USERS" INTEGER,
    "NUM_MAX_TEMPLATES" INTEGER,
    "JSON_FEATURES" JSONB NOT NULL DEFAULT '[]',
    "BOOL_IS_ACTIVE_PLAN" BOOLEAN NOT NULL DEFAULT true,
    "NUM_SORT_ORDER_PLAN" INTEGER NOT NULL DEFAULT 0,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SUBSCRIPTION_PLAN_pkey" PRIMARY KEY ("UID_SUBSCRIPTION_PLAN")
);

-- CreateTable
CREATE TABLE "SUBSCRIPTION" (
    "UID_SUBSCRIPTION" TEXT NOT NULL,
    "UID_FIRM" TEXT NOT NULL,
    "UID_SUBSCRIPTION_PLAN" TEXT NOT NULL,
    "STR_STATUS_SUBSCRIPTION" "SubscriptionStatus" NOT NULL DEFAULT 'TRIAL',
    "STR_BILLING_CYCLE" "BillingCycle" NOT NULL DEFAULT 'MONTHLY',
    "DTM_START_DATE" TIMESTAMP(3) NOT NULL,
    "DTM_END_DATE" TIMESTAMP(3),
    "DTM_TRIAL_ENDS_AT" TIMESTAMP(3),
    "DTM_CANCELLED_AT" TIMESTAMP(3),
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SUBSCRIPTION_pkey" PRIMARY KEY ("UID_SUBSCRIPTION")
);

-- CreateTable
CREATE TABLE "INVOICE" (
    "UID_INVOICE" TEXT NOT NULL,
    "NUM_ID_INVOICE" SERIAL NOT NULL,
    "UID_FIRM" TEXT NOT NULL,
    "UID_SUBSCRIPTION" TEXT,
    "STR_INVOICE_NUMBER" TEXT NOT NULL,
    "NUM_AMOUNT_INVOICE" DECIMAL(65,30) NOT NULL,
    "STR_CURRENCY_INVOICE" TEXT NOT NULL DEFAULT 'COP',
    "STR_STATUS_INVOICE" "InvoiceStatus" NOT NULL DEFAULT 'PENDING',
    "DTM_BILLING_PERIOD_START" TIMESTAMP(3),
    "DTM_BILLING_PERIOD_END" TIMESTAMP(3),
    "DTM_DUE_DATE_INVOICE" TIMESTAMP(3),
    "DTM_PAID_AT_INVOICE" TIMESTAMP(3),
    "STR_PDF_URL_INVOICE" TEXT,
    "STR_EXTERNAL_ID_INVOICE" TEXT,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "INVOICE_pkey" PRIMARY KEY ("UID_INVOICE")
);

-- CreateTable
CREATE TABLE "PAYMENT_METHOD" (
    "UID_PAYMENT_METHOD" TEXT NOT NULL,
    "UID_FIRM" TEXT NOT NULL,
    "STR_TYPE_PAYMENT_METHOD" "PaymentMethodType" NOT NULL,
    "STR_LAST_FOUR" TEXT,
    "STR_BRAND_PAYMENT_METHOD" TEXT,
    "STR_HOLDER_NAME" TEXT,
    "NUM_EXPIRY_MONTH" INTEGER,
    "NUM_EXPIRY_YEAR" INTEGER,
    "BOOL_IS_DEFAULT_PAYMENT" BOOLEAN NOT NULL DEFAULT false,
    "STR_EXTERNAL_ID_PAYMENT" TEXT,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PAYMENT_METHOD_pkey" PRIMARY KEY ("UID_PAYMENT_METHOD")
);

-- CreateTable
CREATE TABLE "LOG" (
    "UID_LOG" TEXT NOT NULL,
    "NUM_ID_LOG" SERIAL NOT NULL,
    "UID_USER" TEXT,
    "STR_LEVEL_LOG" "LogLevel" NOT NULL DEFAULT 'INFO',
    "STR_CONTEXT_LOG" "LogContext" NOT NULL DEFAULT 'SYSTEM',
    "STR_ACTION_LOG" "ActionType" NOT NULL DEFAULT 'READ',
    "STR_MESSAGE_LOG" TEXT NOT NULL DEFAULT '',
    "STR_DESCRIPTION_LOG" TEXT,
    "STR_HTTP_METHOD" TEXT,
    "STR_URL_LOG" TEXT,
    "NUM_STATUS_CODE" INTEGER,
    "NUM_RESPONSE_TIME_MS" INTEGER,
    "STR_IP_ADDRESS" TEXT,
    "STR_USER_AGENT" TEXT,
    "STR_REQUEST_ID" TEXT,
    "STR_SESSION_ID" TEXT,
    "JSON_ADDITIONAL_DATA" JSONB,
    "DTM_TIMESTAMP_LOG" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "LOG_pkey" PRIMARY KEY ("UID_LOG")
);

-- CreateIndex
CREATE UNIQUE INDEX "USER_NUM_ID_USER_key" ON "USER"("NUM_ID_USER");

-- CreateIndex
CREATE UNIQUE INDEX "USER_STR_EMAIL_USER_key" ON "USER"("STR_EMAIL_USER");

-- CreateIndex
CREATE UNIQUE INDEX "CREDENTIALS_UID_USER_key" ON "CREDENTIALS"("UID_USER");

-- CreateIndex
CREATE UNIQUE INDEX "CREDENTIALS_STR_EMAIL_CREDENTIALS_key" ON "CREDENTIALS"("STR_EMAIL_CREDENTIALS");

-- CreateIndex
CREATE INDEX "REFRESH_TOKEN_UID_CREDENTIALS_idx" ON "REFRESH_TOKEN"("UID_CREDENTIALS");

-- CreateIndex
CREATE INDEX "REFRESH_TOKEN_STR_TOKEN_HASH_idx" ON "REFRESH_TOKEN"("STR_TOKEN_HASH");

-- CreateIndex
CREATE UNIQUE INDEX "NOTIFICATION_PREFERENCES_UID_USER_key" ON "NOTIFICATION_PREFERENCES"("UID_USER");

-- CreateIndex
CREATE UNIQUE INDEX "SECURITY_SETTINGS_UID_USER_key" ON "SECURITY_SETTINGS"("UID_USER");

-- CreateIndex
CREATE UNIQUE INDEX "FIRM_NUM_ID_FIRM_key" ON "FIRM"("NUM_ID_FIRM");

-- CreateIndex
CREATE INDEX "FIRM_MEMBER_UID_FIRM_idx" ON "FIRM_MEMBER"("UID_FIRM");

-- CreateIndex
CREATE INDEX "FIRM_MEMBER_STR_INVITE_TOKEN_idx" ON "FIRM_MEMBER"("STR_INVITE_TOKEN");

-- CreateIndex
CREATE UNIQUE INDEX "FIRM_MEMBER_UID_FIRM_UID_USER_key" ON "FIRM_MEMBER"("UID_FIRM", "UID_USER");

-- CreateIndex
CREATE INDEX "LEGAL_BRANCH_UID_FIRM_idx" ON "LEGAL_BRANCH"("UID_FIRM");

-- CreateIndex
CREATE INDEX "LEGAL_BRANCH_BOOL_IS_SYSTEM_BRANCH_idx" ON "LEGAL_BRANCH"("BOOL_IS_SYSTEM_BRANCH");

-- CreateIndex
CREATE UNIQUE INDEX "LEGAL_BRANCH_STR_SLUG_LEGAL_BRANCH_UID_FIRM_key" ON "LEGAL_BRANCH"("STR_SLUG_LEGAL_BRANCH", "UID_FIRM");

-- CreateIndex
CREATE INDEX "DOCUMENT_TEMPLATE_UID_LEGAL_BRANCH_idx" ON "DOCUMENT_TEMPLATE"("UID_LEGAL_BRANCH");

-- CreateIndex
CREATE INDEX "DOCUMENT_TEMPLATE_UID_FIRM_idx" ON "DOCUMENT_TEMPLATE"("UID_FIRM");

-- CreateIndex
CREATE INDEX "DOCUMENT_TEMPLATE_STR_DOCUMENT_TYPE_idx" ON "DOCUMENT_TEMPLATE"("STR_DOCUMENT_TYPE");

-- CreateIndex
CREATE INDEX "DOCUMENT_TEMPLATE_STR_ORIGIN_TEMPLATE_idx" ON "DOCUMENT_TEMPLATE"("STR_ORIGIN_TEMPLATE");

-- CreateIndex
CREATE UNIQUE INDEX "TEMPLATE_FAVORITE_UID_DOCUMENT_TEMPLATE_UID_USER_key" ON "TEMPLATE_FAVORITE"("UID_DOCUMENT_TEMPLATE", "UID_USER");

-- CreateIndex
CREATE UNIQUE INDEX "DOCUMENT_NUM_ID_DOCUMENT_key" ON "DOCUMENT"("NUM_ID_DOCUMENT");

-- CreateIndex
CREATE INDEX "DOCUMENT_UID_FIRM_idx" ON "DOCUMENT"("UID_FIRM");

-- CreateIndex
CREATE INDEX "DOCUMENT_STR_STATUS_DOCUMENT_idx" ON "DOCUMENT"("STR_STATUS_DOCUMENT");

-- CreateIndex
CREATE INDEX "DOCUMENT_DTM_DELETED_AT_idx" ON "DOCUMENT"("DTM_DELETED_AT");

-- CreateIndex
CREATE INDEX "DOCUMENT_UID_CREATED_BY_idx" ON "DOCUMENT"("UID_CREATED_BY");

-- CreateIndex
CREATE INDEX "DOCUMENT_UID_LEGAL_BRANCH_idx" ON "DOCUMENT"("UID_LEGAL_BRANCH");

-- CreateIndex
CREATE INDEX "DIGITAL_SIGNATURE_UID_USER_idx" ON "DIGITAL_SIGNATURE"("UID_USER");

-- CreateIndex
CREATE UNIQUE INDEX "SUBSCRIPTION_PLAN_STR_NAME_PLAN_key" ON "SUBSCRIPTION_PLAN"("STR_NAME_PLAN");

-- CreateIndex
CREATE UNIQUE INDEX "SUBSCRIPTION_UID_FIRM_key" ON "SUBSCRIPTION"("UID_FIRM");

-- CreateIndex
CREATE UNIQUE INDEX "INVOICE_NUM_ID_INVOICE_key" ON "INVOICE"("NUM_ID_INVOICE");

-- CreateIndex
CREATE UNIQUE INDEX "INVOICE_STR_INVOICE_NUMBER_key" ON "INVOICE"("STR_INVOICE_NUMBER");

-- CreateIndex
CREATE INDEX "INVOICE_UID_FIRM_idx" ON "INVOICE"("UID_FIRM");

-- CreateIndex
CREATE INDEX "PAYMENT_METHOD_UID_FIRM_idx" ON "PAYMENT_METHOD"("UID_FIRM");

-- CreateIndex
CREATE INDEX "LOG_DTM_TIMESTAMP_LOG_idx" ON "LOG"("DTM_TIMESTAMP_LOG");

-- CreateIndex
CREATE INDEX "LOG_STR_LEVEL_LOG_idx" ON "LOG"("STR_LEVEL_LOG");

-- CreateIndex
CREATE INDEX "LOG_STR_CONTEXT_LOG_idx" ON "LOG"("STR_CONTEXT_LOG");

-- CreateIndex
CREATE INDEX "LOG_UID_USER_idx" ON "LOG"("UID_USER");

-- CreateIndex
CREATE INDEX "LOG_UID_USER_DTM_TIMESTAMP_LOG_idx" ON "LOG"("UID_USER", "DTM_TIMESTAMP_LOG");

-- AddForeignKey
ALTER TABLE "CREDENTIALS" ADD CONSTRAINT "CREDENTIALS_UID_USER_fkey" FOREIGN KEY ("UID_USER") REFERENCES "USER"("UID_USER") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "REFRESH_TOKEN" ADD CONSTRAINT "REFRESH_TOKEN_UID_CREDENTIALS_fkey" FOREIGN KEY ("UID_CREDENTIALS") REFERENCES "CREDENTIALS"("UID_CREDENTIALS") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NOTIFICATION_PREFERENCES" ADD CONSTRAINT "NOTIFICATION_PREFERENCES_UID_USER_fkey" FOREIGN KEY ("UID_USER") REFERENCES "USER"("UID_USER") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SECURITY_SETTINGS" ADD CONSTRAINT "SECURITY_SETTINGS_UID_USER_fkey" FOREIGN KEY ("UID_USER") REFERENCES "USER"("UID_USER") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FIRM_SPECIALTY" ADD CONSTRAINT "FIRM_SPECIALTY_UID_FIRM_fkey" FOREIGN KEY ("UID_FIRM") REFERENCES "FIRM"("UID_FIRM") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FIRM_MEMBER" ADD CONSTRAINT "FIRM_MEMBER_UID_FIRM_fkey" FOREIGN KEY ("UID_FIRM") REFERENCES "FIRM"("UID_FIRM") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FIRM_MEMBER" ADD CONSTRAINT "FIRM_MEMBER_UID_USER_fkey" FOREIGN KEY ("UID_USER") REFERENCES "USER"("UID_USER") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LEGAL_BRANCH" ADD CONSTRAINT "LEGAL_BRANCH_UID_FIRM_fkey" FOREIGN KEY ("UID_FIRM") REFERENCES "FIRM"("UID_FIRM") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCUMENT_TEMPLATE" ADD CONSTRAINT "DOCUMENT_TEMPLATE_UID_LEGAL_BRANCH_fkey" FOREIGN KEY ("UID_LEGAL_BRANCH") REFERENCES "LEGAL_BRANCH"("UID_LEGAL_BRANCH") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCUMENT_TEMPLATE" ADD CONSTRAINT "DOCUMENT_TEMPLATE_UID_FIRM_fkey" FOREIGN KEY ("UID_FIRM") REFERENCES "FIRM"("UID_FIRM") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCUMENT_TEMPLATE" ADD CONSTRAINT "DOCUMENT_TEMPLATE_UID_PARENT_TEMPLATE_fkey" FOREIGN KEY ("UID_PARENT_TEMPLATE") REFERENCES "DOCUMENT_TEMPLATE"("UID_DOCUMENT_TEMPLATE") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TEMPLATE_FAVORITE" ADD CONSTRAINT "TEMPLATE_FAVORITE_UID_DOCUMENT_TEMPLATE_fkey" FOREIGN KEY ("UID_DOCUMENT_TEMPLATE") REFERENCES "DOCUMENT_TEMPLATE"("UID_DOCUMENT_TEMPLATE") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TEMPLATE_FAVORITE" ADD CONSTRAINT "TEMPLATE_FAVORITE_UID_USER_fkey" FOREIGN KEY ("UID_USER") REFERENCES "USER"("UID_USER") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCUMENT" ADD CONSTRAINT "DOCUMENT_UID_DOCUMENT_TEMPLATE_fkey" FOREIGN KEY ("UID_DOCUMENT_TEMPLATE") REFERENCES "DOCUMENT_TEMPLATE"("UID_DOCUMENT_TEMPLATE") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCUMENT" ADD CONSTRAINT "DOCUMENT_UID_LEGAL_BRANCH_fkey" FOREIGN KEY ("UID_LEGAL_BRANCH") REFERENCES "LEGAL_BRANCH"("UID_LEGAL_BRANCH") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCUMENT" ADD CONSTRAINT "DOCUMENT_UID_FIRM_fkey" FOREIGN KEY ("UID_FIRM") REFERENCES "FIRM"("UID_FIRM") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DOCUMENT" ADD CONSTRAINT "DOCUMENT_UID_CREATED_BY_fkey" FOREIGN KEY ("UID_CREATED_BY") REFERENCES "USER"("UID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DIGITAL_SIGNATURE" ADD CONSTRAINT "DIGITAL_SIGNATURE_UID_USER_fkey" FOREIGN KEY ("UID_USER") REFERENCES "USER"("UID_USER") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SUBSCRIPTION" ADD CONSTRAINT "SUBSCRIPTION_UID_FIRM_fkey" FOREIGN KEY ("UID_FIRM") REFERENCES "FIRM"("UID_FIRM") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SUBSCRIPTION" ADD CONSTRAINT "SUBSCRIPTION_UID_SUBSCRIPTION_PLAN_fkey" FOREIGN KEY ("UID_SUBSCRIPTION_PLAN") REFERENCES "SUBSCRIPTION_PLAN"("UID_SUBSCRIPTION_PLAN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INVOICE" ADD CONSTRAINT "INVOICE_UID_FIRM_fkey" FOREIGN KEY ("UID_FIRM") REFERENCES "FIRM"("UID_FIRM") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INVOICE" ADD CONSTRAINT "INVOICE_UID_SUBSCRIPTION_fkey" FOREIGN KEY ("UID_SUBSCRIPTION") REFERENCES "SUBSCRIPTION"("UID_SUBSCRIPTION") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PAYMENT_METHOD" ADD CONSTRAINT "PAYMENT_METHOD_UID_FIRM_fkey" FOREIGN KEY ("UID_FIRM") REFERENCES "FIRM"("UID_FIRM") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LOG" ADD CONSTRAINT "LOG_UID_USER_fkey" FOREIGN KEY ("UID_USER") REFERENCES "USER"("UID_USER") ON DELETE SET NULL ON UPDATE CASCADE;
