-- CreateEnum
CREATE TYPE "TimeEntryType" AS ENUM ('AUTO', 'MANUAL');

-- CreateTable
CREATE TABLE "TIME_ENTRY" (
    "UID_TIME_ENTRY" TEXT NOT NULL,
    "NUM_ID_TIME_ENTRY" SERIAL NOT NULL,
    "UID_LEGAL_PROCESS" TEXT NOT NULL,
    "UID_USER" TEXT NOT NULL,
    "UID_FIRM" TEXT NOT NULL,
    "STR_TYPE_TIME_ENTRY" "TimeEntryType" NOT NULL DEFAULT 'MANUAL',
    "STR_DESCRIPTION_TIME_ENTRY" TEXT,
    "DTM_STARTED_AT_TIME_ENTRY" TIMESTAMP(3) NOT NULL,
    "DTM_ENDED_AT_TIME_ENTRY" TIMESTAMP(3),
    "NUM_DURATION_MINUTES_TIME_ENTRY" INTEGER,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TIME_ENTRY_pkey" PRIMARY KEY ("UID_TIME_ENTRY")
);

-- CreateIndex
CREATE UNIQUE INDEX "TIME_ENTRY_NUM_ID_TIME_ENTRY_key" ON "TIME_ENTRY"("NUM_ID_TIME_ENTRY");

-- CreateIndex
CREATE INDEX "TIME_ENTRY_UID_LEGAL_PROCESS_idx" ON "TIME_ENTRY"("UID_LEGAL_PROCESS");

-- CreateIndex
CREATE INDEX "TIME_ENTRY_UID_USER_idx" ON "TIME_ENTRY"("UID_USER");

-- CreateIndex
CREATE INDEX "TIME_ENTRY_UID_FIRM_idx" ON "TIME_ENTRY"("UID_FIRM");

-- CreateIndex
CREATE INDEX "TIME_ENTRY_DTM_ENDED_AT_TIME_ENTRY_idx" ON "TIME_ENTRY"("DTM_ENDED_AT_TIME_ENTRY");

-- AddForeignKey
ALTER TABLE "TIME_ENTRY" ADD CONSTRAINT "TIME_ENTRY_UID_LEGAL_PROCESS_fkey" FOREIGN KEY ("UID_LEGAL_PROCESS") REFERENCES "LEGAL_PROCESS"("UID_LEGAL_PROCESS") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TIME_ENTRY" ADD CONSTRAINT "TIME_ENTRY_UID_USER_fkey" FOREIGN KEY ("UID_USER") REFERENCES "USER"("UID_USER") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TIME_ENTRY" ADD CONSTRAINT "TIME_ENTRY_UID_FIRM_fkey" FOREIGN KEY ("UID_FIRM") REFERENCES "FIRM"("UID_FIRM") ON DELETE CASCADE ON UPDATE CASCADE;
