-- CreateEnum
CREATE TYPE "LegalUpdateSource" AS ENUM ('CORTE_CONSTITUCIONAL', 'CORTE_SUPREMA', 'PRESIDENCIA_NORMATIVA', 'ACTUALICESE', 'ASUNTOS_LEGALES', 'SUIN_JURISCOL', 'AMBITO_JURIDICO', 'DIARIO_OFICIAL', 'CORTE_CONST_COMUNICADOS');

-- CreateEnum
CREATE TYPE "LegalUpdateType" AS ENUM ('LAW', 'DECREE', 'RESOLUTION', 'CIRCULAR', 'RULING', 'JURISPRUDENCE', 'NEWS', 'OTHER');

-- CreateTable
CREATE TABLE "LEGAL_UPDATE" (
    "UID_LEGAL_UPDATE" TEXT NOT NULL,
    "NUM_ID_LEGAL_UPDATE" SERIAL NOT NULL,
    "STR_SOURCE_LEGAL_UPDATE" "LegalUpdateSource" NOT NULL,
    "STR_SOURCE_LABEL_LEGAL_UPDATE" TEXT NOT NULL,
    "STR_EXTERNAL_ID_LEGAL_UPDATE" TEXT NOT NULL,
    "STR_TYPE_LEGAL_UPDATE" "LegalUpdateType" NOT NULL DEFAULT 'NEWS',
    "STR_TITLE_LEGAL_UPDATE" TEXT NOT NULL,
    "STR_SUMMARY_LEGAL_UPDATE" TEXT,
    "STR_URL_LEGAL_UPDATE" TEXT NOT NULL,
    "STR_CATEGORY_LEGAL_UPDATE" TEXT,
    "UID_LEGAL_BRANCH_LEGAL_UPDATE" TEXT,
    "DTM_PUBLISHED_AT_LEGAL_UPDATE" TIMESTAMP(3) NOT NULL,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "LEGAL_UPDATE_pkey" PRIMARY KEY ("UID_LEGAL_UPDATE")
);

-- CreateTable
CREATE TABLE "LEGAL_UPDATE_SOURCE_RUN" (
    "UID_LEGAL_UPDATE_SOURCE_RUN" TEXT NOT NULL,
    "STR_SOURCE_LEGAL_UPDATE_SOURCE_RUN" "LegalUpdateSource" NOT NULL,
    "DTM_LAST_RUN_AT_LEGAL_UPDATE_SOURCE_RUN" TIMESTAMP(3),
    "DTM_LAST_OK_AT_LEGAL_UPDATE_SOURCE_RUN" TIMESTAMP(3),
    "STR_LAST_ERROR_LEGAL_UPDATE_SOURCE_RUN" TEXT,
    "STR_LAST_CURSOR_LEGAL_UPDATE_SOURCE_RUN" TEXT,
    "NUM_ITEMS_LAST_RUN_LEGAL_UPDATE_SOURCE_RUN" INTEGER NOT NULL DEFAULT 0,
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "LEGAL_UPDATE_SOURCE_RUN_pkey" PRIMARY KEY ("UID_LEGAL_UPDATE_SOURCE_RUN")
);

-- CreateIndex
CREATE INDEX "LEGAL_UPDATE_DTM_PUBLISHED_AT_LEGAL_UPDATE_idx" ON "LEGAL_UPDATE"("DTM_PUBLISHED_AT_LEGAL_UPDATE");

-- CreateIndex
CREATE INDEX "LEGAL_UPDATE_STR_SOURCE_LEGAL_UPDATE_idx" ON "LEGAL_UPDATE"("STR_SOURCE_LEGAL_UPDATE");

-- CreateIndex
CREATE INDEX "LEGAL_UPDATE_UID_LEGAL_BRANCH_LEGAL_UPDATE_idx" ON "LEGAL_UPDATE"("UID_LEGAL_BRANCH_LEGAL_UPDATE");

-- CreateIndex
CREATE UNIQUE INDEX "LEGAL_UPDATE_STR_SOURCE_LEGAL_UPDATE_STR_EXTERNAL_ID_LEGAL__key" ON "LEGAL_UPDATE"("STR_SOURCE_LEGAL_UPDATE", "STR_EXTERNAL_ID_LEGAL_UPDATE");

-- CreateIndex
CREATE UNIQUE INDEX "LEGAL_UPDATE_SOURCE_RUN_STR_SOURCE_LEGAL_UPDATE_SOURCE_RUN_key" ON "LEGAL_UPDATE_SOURCE_RUN"("STR_SOURCE_LEGAL_UPDATE_SOURCE_RUN");

-- AddForeignKey
ALTER TABLE "LEGAL_UPDATE" ADD CONSTRAINT "LEGAL_UPDATE_UID_LEGAL_BRANCH_LEGAL_UPDATE_fkey" FOREIGN KEY ("UID_LEGAL_BRANCH_LEGAL_UPDATE") REFERENCES "LEGAL_BRANCH"("UID_LEGAL_BRANCH") ON DELETE SET NULL ON UPDATE CASCADE;
