/*
  Warnings:

  - You are about to drop the column `UID_PROCESS_TIMELINE_EVENT` on the `PROCESS_TIMELINE_ATTACHMENT` table. All the data in the column will be lost.
  - You are about to drop the column `UID_PROCESS_TIMELINE_EVENT` on the `PROCESS_TIMELINE_REMINDER` table. All the data in the column will be lost.
  - You are about to drop the `PROCESS_TIMELINE_EVENT` table. If the table is not empty, all the data it contains will be lost.
  - Added the required column `UID_PROCESS_TIMELINE_COMMENT` to the `PROCESS_TIMELINE_ATTACHMENT` table without a default value. This is not possible if the table is not empty.
  - Added the required column `UID_PROCESS_TIMELINE_COMMENT` to the `PROCESS_TIMELINE_REMINDER` table without a default value. This is not possible if the table is not empty.

*/
-- CreateEnum
CREATE TYPE "TimelineStage" AS ENUM ('DEMANDA', 'NOTIFICACION', 'CONTESTACION', 'AUDIENCIA', 'SENTENCIA', 'RECURSO');

-- DropForeignKey
ALTER TABLE "PROCESS_TIMELINE_ATTACHMENT" DROP CONSTRAINT "PROCESS_TIMELINE_ATTACHMENT_UID_PROCESS_TIMELINE_EVENT_fkey";

-- DropForeignKey
ALTER TABLE "PROCESS_TIMELINE_EVENT" DROP CONSTRAINT "PROCESS_TIMELINE_EVENT_UID_CREATED_BY_PROCESS_TIMELINE_EVE_fkey";

-- DropForeignKey
ALTER TABLE "PROCESS_TIMELINE_EVENT" DROP CONSTRAINT "PROCESS_TIMELINE_EVENT_UID_LEGAL_PROCESS_fkey";

-- DropForeignKey
ALTER TABLE "PROCESS_TIMELINE_EVENT" DROP CONSTRAINT "PROCESS_TIMELINE_EVENT_UID_RESPONSIBLE_PROCESS_TIMELINE_EV_fkey";

-- DropForeignKey
ALTER TABLE "PROCESS_TIMELINE_REMINDER" DROP CONSTRAINT "PROCESS_TIMELINE_REMINDER_UID_PROCESS_TIMELINE_EVENT_fkey";

-- DropIndex
DROP INDEX "PROCESS_TIMELINE_ATTACHMENT_UID_PROCESS_TIMELINE_EVENT_idx";

-- DropIndex
DROP INDEX "PROCESS_TIMELINE_REMINDER_UID_PROCESS_TIMELINE_EVENT_idx";

-- AlterTable
ALTER TABLE "PROCESS_TIMELINE_ATTACHMENT" DROP COLUMN "UID_PROCESS_TIMELINE_EVENT",
ADD COLUMN     "UID_PROCESS_TIMELINE_COMMENT" TEXT NOT NULL;

-- AlterTable
ALTER TABLE "PROCESS_TIMELINE_REMINDER" DROP COLUMN "UID_PROCESS_TIMELINE_EVENT",
ADD COLUMN     "UID_PROCESS_TIMELINE_COMMENT" TEXT NOT NULL;

-- DropTable
DROP TABLE "PROCESS_TIMELINE_EVENT";

-- DropEnum
DROP TYPE "ProcessTimelineEventStatus";

-- DropEnum
DROP TYPE "ProcessTimelineEventType";

-- CreateTable
CREATE TABLE "PROCESS_TIMELINE_STAGE" (
    "UID_PROCESS_TIMELINE_STAGE" TEXT NOT NULL,
    "NUM_ID_PROCESS_TIMELINE_STAGE" SERIAL NOT NULL,
    "UID_LEGAL_PROCESS" TEXT NOT NULL,
    "UID_FIRM" TEXT NOT NULL,
    "STR_STAGE_PROCESS_TIMELINE_STAGE" "TimelineStage" NOT NULL,
    "STR_MICRO_STAGE_LABEL_PROCESS_TIMELINE_STAGE" TEXT,
    "UID_CREATED_BY_PROCESS_TIMELINE_STAGE" TEXT NOT NULL,
    "DTM_DELETED_AT_PROCESS_TIMELINE_STAGE" TIMESTAMP(3),
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PROCESS_TIMELINE_STAGE_pkey" PRIMARY KEY ("UID_PROCESS_TIMELINE_STAGE")
);

-- CreateTable
CREATE TABLE "PROCESS_TIMELINE_COMMENT" (
    "UID_PROCESS_TIMELINE_COMMENT" TEXT NOT NULL,
    "NUM_ID_PROCESS_TIMELINE_COMMENT" SERIAL NOT NULL,
    "UID_PROCESS_TIMELINE_STAGE" TEXT NOT NULL,
    "UID_LEGAL_PROCESS" TEXT NOT NULL,
    "STR_BODY_PROCESS_TIMELINE_COMMENT" TEXT NOT NULL,
    "DTM_COMMENT_DATE_PROCESS_TIMELINE_COMMENT" TIMESTAMP(3) NOT NULL,
    "UID_RESPONSIBLE_PROCESS_TIMELINE_COMMENT" TEXT,
    "UID_CREATED_BY_PROCESS_TIMELINE_COMMENT" TEXT NOT NULL,
    "DTM_DELETED_AT_PROCESS_TIMELINE_COMMENT" TIMESTAMP(3),
    "DTM_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DTM_UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PROCESS_TIMELINE_COMMENT_pkey" PRIMARY KEY ("UID_PROCESS_TIMELINE_COMMENT")
);

-- CreateIndex
CREATE INDEX "PROCESS_TIMELINE_STAGE_UID_LEGAL_PROCESS_idx" ON "PROCESS_TIMELINE_STAGE"("UID_LEGAL_PROCESS");

-- CreateIndex
CREATE INDEX "PROCESS_TIMELINE_STAGE_DTM_DELETED_AT_PROCESS_TIMELINE_STAG_idx" ON "PROCESS_TIMELINE_STAGE"("DTM_DELETED_AT_PROCESS_TIMELINE_STAGE");

-- CreateIndex
CREATE INDEX "PROCESS_TIMELINE_COMMENT_UID_PROCESS_TIMELINE_STAGE_idx" ON "PROCESS_TIMELINE_COMMENT"("UID_PROCESS_TIMELINE_STAGE");

-- CreateIndex
CREATE INDEX "PROCESS_TIMELINE_COMMENT_UID_LEGAL_PROCESS_idx" ON "PROCESS_TIMELINE_COMMENT"("UID_LEGAL_PROCESS");

-- CreateIndex
CREATE INDEX "PROCESS_TIMELINE_COMMENT_DTM_DELETED_AT_PROCESS_TIMELINE_CO_idx" ON "PROCESS_TIMELINE_COMMENT"("DTM_DELETED_AT_PROCESS_TIMELINE_COMMENT");

-- CreateIndex
CREATE INDEX "PROCESS_TIMELINE_ATTACHMENT_UID_PROCESS_TIMELINE_COMMENT_idx" ON "PROCESS_TIMELINE_ATTACHMENT"("UID_PROCESS_TIMELINE_COMMENT");

-- CreateIndex
CREATE INDEX "PROCESS_TIMELINE_REMINDER_UID_PROCESS_TIMELINE_COMMENT_idx" ON "PROCESS_TIMELINE_REMINDER"("UID_PROCESS_TIMELINE_COMMENT");

-- AddForeignKey
ALTER TABLE "PROCESS_TIMELINE_STAGE" ADD CONSTRAINT "PROCESS_TIMELINE_STAGE_UID_LEGAL_PROCESS_fkey" FOREIGN KEY ("UID_LEGAL_PROCESS") REFERENCES "LEGAL_PROCESS"("UID_LEGAL_PROCESS") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROCESS_TIMELINE_STAGE" ADD CONSTRAINT "PROCESS_TIMELINE_STAGE_UID_CREATED_BY_PROCESS_TIMELINE_STA_fkey" FOREIGN KEY ("UID_CREATED_BY_PROCESS_TIMELINE_STAGE") REFERENCES "USER"("UID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROCESS_TIMELINE_COMMENT" ADD CONSTRAINT "PROCESS_TIMELINE_COMMENT_UID_PROCESS_TIMELINE_STAGE_fkey" FOREIGN KEY ("UID_PROCESS_TIMELINE_STAGE") REFERENCES "PROCESS_TIMELINE_STAGE"("UID_PROCESS_TIMELINE_STAGE") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROCESS_TIMELINE_COMMENT" ADD CONSTRAINT "PROCESS_TIMELINE_COMMENT_UID_LEGAL_PROCESS_fkey" FOREIGN KEY ("UID_LEGAL_PROCESS") REFERENCES "LEGAL_PROCESS"("UID_LEGAL_PROCESS") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROCESS_TIMELINE_COMMENT" ADD CONSTRAINT "PROCESS_TIMELINE_COMMENT_UID_RESPONSIBLE_PROCESS_TIMELINE__fkey" FOREIGN KEY ("UID_RESPONSIBLE_PROCESS_TIMELINE_COMMENT") REFERENCES "FIRM_MEMBER"("UID_FIRM_MEMBER") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROCESS_TIMELINE_COMMENT" ADD CONSTRAINT "PROCESS_TIMELINE_COMMENT_UID_CREATED_BY_PROCESS_TIMELINE_C_fkey" FOREIGN KEY ("UID_CREATED_BY_PROCESS_TIMELINE_COMMENT") REFERENCES "USER"("UID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROCESS_TIMELINE_ATTACHMENT" ADD CONSTRAINT "PROCESS_TIMELINE_ATTACHMENT_UID_PROCESS_TIMELINE_COMMENT_fkey" FOREIGN KEY ("UID_PROCESS_TIMELINE_COMMENT") REFERENCES "PROCESS_TIMELINE_COMMENT"("UID_PROCESS_TIMELINE_COMMENT") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PROCESS_TIMELINE_REMINDER" ADD CONSTRAINT "PROCESS_TIMELINE_REMINDER_UID_PROCESS_TIMELINE_COMMENT_fkey" FOREIGN KEY ("UID_PROCESS_TIMELINE_COMMENT") REFERENCES "PROCESS_TIMELINE_COMMENT"("UID_PROCESS_TIMELINE_COMMENT") ON DELETE CASCADE ON UPDATE CASCADE;
